---
title: "Creating the Final Data"
author: "Eugenio Paglino"
date: "\today"
output:
  html_document
---

```{r, echo=F, include=F}

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

```

```{r}

# Loading necessary packages

library(tidyverse)
library(lubridate)
library(here)

# Set seed for the Rmd

set.seed(42)

```

```{r}

# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running

rm(list=ls())

here::i_am('R/dataCreation.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r}

FIPSFixes <- read_csv(here::here(inDir,'FIPSHarmonization','FIPSFixes.csv'))

```

```{r}

read_CDC_data <- function(file) {
  
  data <- list.files(
      file,
      pattern = "*.txt",
      full.names = TRUE
    ) %>%
    map_dfr(
      ~ data.table::fread(
        .x,
        na.strings = c("Missing", "Suppressed", "Not Applicable"),
        keepLeadingZeros = TRUE,
        colClasses = c("character")
      )
    )

  data <- as.tibble(data)
  return(data)
  
}

fix_FIPS <- function(FIPSFixes,data) {
  
  data <- data %>%
    left_join(FIPSFixes,by='FIPSCode') %>%
    mutate(FIPSCode = if_else(is.na(newFIPSCode),FIPSCode,newFIPSCode)) %>%
    select(-newFIPSCode) 
  
  return(data)
  
}

```

```{r}

# Import historical county-month data downloaded from CDC WONDER
# https://wonder.cdc.gov/ucd-icd10.html
# NOTE: County-months with < 10 deaths are censored in these data

ACData <- read_CDC_data(here(inDir,'CDC','AllCausesMonthly'))

# Setting intuitive names

ACData <- ACData %>%
  select('FIPSCode'='County Code',
         'monthCode'='Month Code',
         'deaths'='Deaths',
         'FIPSCode2021'='Residence County Code')

ACData <- ACData %>% 
  mutate(FIPSCode = coalesce(FIPSCode, FIPSCode2021))

# Keeping only the variables we need

ACData <- ACData %>% select(FIPSCode,monthCode,deaths)

# We extract month and year from the monthCode variable and then
# create a monthYear date variable.

ACData <- ACData %>% 
  separate(monthCode, into=c('year','month')) %>%
  mutate(across(c(deaths,year,month),as.integer))

# We harmonize the FIPS codes

ACData <- fix_FIPS(FIPSFixes,ACData) 

```

```{r}

# Import historical county-year data downloaded from CDC WONDER
# https://wonder.cdc.gov/ucd-icd10.html
# NOTE: County-years with < 10 deaths are censored in these data

ACYearlyData <- read_CDC_data(here(inDir,'CDC','AllCausesYearly'))

ACYearlyData <- ACYearlyData %>%
  select('FIPSCode'='County Code',
         'year'='Year Code',
         'deaths'='Deaths',
         'FIPSCode2021'='Residence County Code')

ACYearlyData <- ACYearlyData %>% 
  mutate(FIPSCode = coalesce(FIPSCode,FIPSCode2021))

# Keeping only the variables we need

ACYearlyData <- ACYearlyData %>% select(FIPSCode,year,deaths)

ACYearlyData <- ACYearlyData %>% 
  mutate(across(c(deaths,year),as.integer))

# We harmonize the FIPS codes

ACYearlyData <- fix_FIPS(FIPSFixes,ACYearlyData) 

```

```{r}

# Import historical county-month data downloaded from CDC WONDER
# https://wonder.cdc.gov/ucd-icd10.html
# NOTE: County-months with < 10 deaths are censored in these data

COVIDYearlyData <- read_CDC_data(here(inDir,'CDC','COVIDUCDYearly'))

# Setting intuitive names

COVIDYearlyData <- COVIDYearlyData %>%
  select('FIPSCode'='Residence County Code',
         'year'='Year Code',
         'COVIDDeaths'='Deaths')

COVIDYearlyData <- COVIDYearlyData %>% 
  mutate(COVIDDeaths = as.integer(COVIDDeaths),
         year = as.integer(year))

# We harmonize the FIPS codes

COVIDYearlyData <- fix_FIPS(FIPSFixes,COVIDYearlyData) 

```

```{r}

# Import historical county-month data downloaded from CDC WONDER
# https://wonder.cdc.gov/ucd-icd10.html
# NOTE: County-months with < 10 deaths are censored in these data

COVIDMonthlyData <- read_CDC_data(here(inDir,'CDC','COVIDUCDMonthly'))

# Setting intuitive names

COVIDMonthlyData <- COVIDMonthlyData %>%
  select('FIPSCode'='Residence County Code',
         'monthCode'='Month Code',
         'COVIDDeaths'='Deaths')

# We extract month and year from the monthCode variable and then
# create a monthYear date variable.

COVIDMonthlyData <- COVIDMonthlyData %>% 
  separate(monthCode, into=c('year','month')) %>%
  mutate(across(c(COVIDDeaths,year,month),as.integer))

# We harmonize the FIPS codes

COVIDMonthlyData <- fix_FIPS(FIPSFixes,COVIDMonthlyData) 

```

```{r}

COVIDPeriodsData <- list.files(
      here(inDir,'CDC','COVIDUCDPeriods'),
      pattern = "*.txt",
      full.names = TRUE
    ) %>%
    map_dfr(
      ~ data.table::fread(
        .x,
        na.strings = c("Missing", "Suppressed", "Not Applicable"),
        keepLeadingZeros = TRUE,
        colClasses = c("character")
      ) %>% mutate (file = .x)
    )

COVIDPeriodsData <- COVIDPeriodsData %>%
  mutate(period = str_match(file,'[\\d]{1}')[,1]) %>%
  select(-file)

COVIDPeriodsData <- COVIDPeriodsData %>%
  select('FIPSCode'='Residence County Code',
         'period'='period',
         'COVIDDeaths'='Deaths') %>%
  mutate(across(c(COVIDDeaths,period),as.integer))


# We harmonize the FIPS codes

COVIDPeriodsData <- fix_FIPS(FIPSFixes,COVIDPeriodsData) 

```


```{r}

# Import population counts and information on county sets (groups of 
# counties created by the Census Bureau to have geographical units with
# at least 50.000 residents).

popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))

popData <- popData %>%
  filter(year>=2010)

countySets <- read_csv(here::here(inDir,'geo','countySets.csv'), 
                       col_types = cols(csCode=col_character(),
                                        csName=col_character(),
                                        countyName=col_character(),
                                        stateFIPS=col_integer(),
                                        countyFIPS=col_integer(),
                                        FIPSCode=col_character()))

states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r}

popDataYearly <- popData %>%
  group_by(FIPSCode,year) %>%
  summarise(pop=mean(pop,na.rm=T)) %>%
  ungroup()

```

```{r}
# We harmonize the FIPS code here too
countySets <- countySets %>%
  left_join(FIPSFixes,by='FIPSCode') %>%
  mutate(FIPSCode = if_else(is.na(newFIPSCode),FIPSCode,newFIPSCode)) %>%
  select(-newFIPSCode) %>%
  mutate(csCode = if_else(FIPSCode == '02140','02CS005',csCode),
         csName = if_else(FIPSCode == '02140','Northern Alaska',csName),
         countyName = if_else(FIPSCode == '02140','Northern Alaska',countyName),
         countyFIPS = if_else(FIPSCode == '02140',140L,countyFIPS),
         csCode = if_else(FIPSCode == '02232','02CS006',csCode),
         csName = if_else(FIPSCode == '02232','Southeast Alaska',csName),
         countyName = if_else(FIPSCode == '02232','Southeast Alaska',countyName),
         countyFIPS = if_else(FIPSCode == '02232',232L,countyFIPS),
         csCode = if_else(FIPSCode == '02010','02CS007',csCode),
         csName = if_else(FIPSCode == '02010','Southwest Alaska',csName),
         countyName = if_else(FIPSCode == '02010','Southwest Alaska',countyName),
         countyFIPS = if_else(FIPSCode == '02010',10L,countyFIPS),
         csCode = if_else(FIPSCode == '02158','02CS007',csCode),
         csName = if_else(FIPSCode == '02158','Southwest Alaska',csName),
         countyName = if_else(FIPSCode == '02158','Southwest Alaska',countyName),
         countyFIPS = if_else(FIPSCode == '02158',158L,countyFIPS),
         csCode = if_else(FIPSCode == '46102','46CS010',csCode),
         csName = if_else(FIPSCode == '46102','Southwest Central South Dakota',csName),
         countyName = if_else(FIPSCode == '46102','Southwest Central South Dakota',countyName),
         countyFIPS = if_else(FIPSCode == '46102',102L,countyFIPS)) %>%
  filter(stateFIPS*1000 + countyFIPS == as.double(FIPSCode)) %>%
  distinct()
```


```{r}

# Construct data frame of state abbreviations + divisions, plus DC
census_divisions <- tibble(
  state = state.name,
  census_division = state.division,
  census_region = state.region
) %>%
  add_row(
    state = "District of Columbia",
    census_division = "South Atlantic",
    census_region = "South"
  )

```

```{r}

# We create two tibbles needed to create complete datasets with all
# county-months or county-years even when the original data is missing
# or suppressed. To fill the missing data when we wish to do so, we 
# create an imputedDeaths variable sampled from a Beta distribution 
# with parameters alpha=2, and beta=2. We multiply each realization from
# this distribution by 9 so that it ranges from 0 to 9 (the potential
# values for suppressed deaths). We apply rounding to the result to
# ensure that we have an integer value.

FIPSCodes <- as.character(unique(popData$FIPSCode))

simData <- crossing(year=2015:2022,
                    month=1:12,
                    FIPSCode=FIPSCodes)

simDataYearly <- crossing(year=2010:2022,
                          FIPSCode=FIPSCodes)

simDataYearly <- simDataYearly %>%
  mutate(imputedDeaths = round(rbeta(nrow(simDataYearly),2.25,2)*9))

simDataPeriods <- crossing(period=1:6,
                           FIPSCode=FIPSCodes)

simDataPeriods <- simDataPeriods %>%
  mutate(imputedDeaths = round(rbeta(nrow(simDataPeriods),2.25,2)*9))

```

```{r}

ACDataComplete <- simData %>%
  left_join(ACData,by=c('FIPSCode','year','month')) %>%
  mutate(monthYear = make_date(year=year,month=month,day=1)) 

```

```{r}

# We add population counts to our data and assign each county to the 
# corresponding county set.

ACDataComplete <- ACDataComplete %>% 
  left_join(popData, by = c('FIPSCode','year','month')) %>%
  left_join(countySets, by = c('FIPSCode')) %>%
  left_join(states, by = c('stateFIPS')) %>%
  left_join(census_divisions,by='state')

# The step below is needed to collapse multiple counties with the same
# harmonized FIPS code into one. So far, the data still contains counties
# assigned to the same harmonized FIPS as separate observations.

# Sum is the appropriate aggregation unit for deaths and inputedDeaths
# because those have a different value for each of these counties.
# Mean is the appropriate aggregation unit for the population because the 
# popData file already uses harmonized counties so that the multiple
# counties with the same harmonized FIPS code already share the same
# population value (corresponding to the sum of the population of all 
# the counties with the same FIPS).

# The same rational applies for the similar cells dealing with the
# yearly all-cause death data and the COVID data

ACDataComplete <- ACDataComplete %>%
  group_by(FIPSCode,countyName,csCode,csName,stateFIPS,state,census_division,year,month) %>%
  summarize(deaths = if_else(sum(is.na(deaths)) == n(), NA_integer_, sum(deaths,na.rm=T)),
            pop = mean(pop)) %>%
  ungroup()

```

```{r}

COVIDMonthlyDataComplete <- simData %>%
  left_join(COVIDMonthlyData,by=c('FIPSCode','year','month')) %>%
  mutate(monthYear = make_date(year=year,month=month,day=1)) %>%
  filter(between(monthYear,make_date(2020,3,1),make_date(2022,2,1))) 

COVIDMonthlyDataComplete <- COVIDMonthlyDataComplete %>%
  mutate(imputedDeaths = round(rbeta(nrow(COVIDMonthlyDataComplete),2.25,2)*9),
         imputedCOVIDDeaths = if_else(is.na(COVIDDeaths),imputedDeaths,as.double(COVIDDeaths))) 


```

```{r}

# We add population counts to our data and assign each county to the 
# corresponding county set.

COVIDMonthlyDataComplete <- COVIDMonthlyDataComplete %>% 
  left_join(popData, by = c('FIPSCode','year','month')) %>%
  left_join(countySets, by = c('FIPSCode')) %>%
  left_join(states, by = c('stateFIPS')) %>%
  left_join(census_divisions,by='state')

# The step below is needed to collapse multiple counties with the same
# harmonized FIPS code into one. So far, the data still contains counties
# assigned to the same harmonized FIPS as separate observations.

# Sum is the appropriate aggregation unit for deaths and inputedDeaths
# because those have a different value for each of these counties.
# Mean is the appropriate aggregation unit for the population because the 
# popData file already uses harmonized counties so that the multiple
# counties with the same harmonized FIPS code already share the same
# population value (corresponding to the sum of the population of all 
# the counties with the same FIPS).

# The same rational applies for the similar cells dealing with the
# yearly all-cause death data and the COVID data

COVIDMonthlyDataComplete <- COVIDMonthlyDataComplete %>%
  group_by(FIPSCode,countyName,csCode,csName,stateFIPS,state,census_division,year,month) %>%
  summarize(COVIDDeaths = if_else(sum(is.na(COVIDDeaths)) == n(), NA_integer_, sum(COVIDDeaths,na.rm=T)),
            imputedCOVIDDeaths = sum(imputedCOVIDDeaths),
            pop = mean(pop)) %>%
  ungroup()

```

```{r}

COVIDPeriodsDataComplete <- simDataPeriods %>%
  left_join(COVIDPeriodsData,by=c('FIPSCode','period')) %>%
  mutate(imputedCOVIDDeaths = if_else(is.na(COVIDDeaths),imputedDeaths,as.double(COVIDDeaths))) 


```

```{r}

# We add population counts to our data and assign each county to the 
# corresponding county set.

COVIDPeriodsDataComplete <- COVIDPeriodsDataComplete %>% 
  left_join(countySets,by=c('FIPSCode')) %>%
  left_join(states, by = c('stateFIPS')) %>%
  left_join(census_divisions,by='state')

# The step below is needed to collapse multiple counties with the same
# harmonized FIPS code into one. So far, the data still contains counties
# assigned to the same harmonized FIPS as separate observations.

# Sum is the appropriate aggregation unit for deaths and inputedDeaths
# because those have a different value for each of these counties.
# Mean is the appropriate aggregation unit for the population because the 
# popData file already uses harmonized counties so that the multiple
# counties with the same harmonized FIPS code already share the same
# population value (corresponding to the sum of the population of all 
# the counties with the same FIPS).

# The same rational applies for the similar cells dealing with the
# yearly all-cause death data and the COVID data

COVIDPeriodsDataComplete <- COVIDPeriodsDataComplete %>%
  group_by(FIPSCode,countyName,csCode,csName,stateFIPS,state,census_division,period) %>%
  summarize(COVIDDeaths = if_else(sum(is.na(COVIDDeaths)) == n(), NA_integer_, sum(COVIDDeaths,na.rm=T)),
            imputedCOVIDDeaths = sum(imputedCOVIDDeaths)) %>%
  ungroup()

```

```{r}

ACYearlyDataComplete <- simDataYearly %>%
  left_join(ACYearlyData,by=c('FIPSCode','year')) %>%
  mutate(imputedDeaths = if_else(is.na(deaths),imputedDeaths,as.double(deaths))) 

```

```{r}

# We add population counts to our data and assign each county to the 
# corresponding county set.

ACYearlyDataComplete <- ACYearlyDataComplete %>% 
  left_join(countySets,by=c('FIPSCode')) %>%
  left_join(popDataYearly, by = c('FIPSCode','year')) %>%
  left_join(states, by = c('stateFIPS')) %>%
  left_join(census_divisions,by='state')


ACYearlyDataComplete <- ACYearlyDataComplete %>%
  group_by(FIPSCode,countyName,csCode,csName,stateFIPS,state,census_division,year) %>%
  summarize(deaths = if_else(sum(is.na(deaths)) == n(), NA_integer_, sum(deaths,na.rm=T)),
            imputedDeaths = sum(imputedDeaths),
            pop = mean(pop)) %>%
  ungroup()

```

```{r}

COVIDYearlyDataComplete <- filter(simDataYearly,year>2019) %>%
  left_join(COVIDYearlyData,by=c('FIPSCode','year')) %>%
  mutate(imputedCOVIDDeaths = if_else(is.na(COVIDDeaths),imputedDeaths,as.double(COVIDDeaths))) 

```

```{r}

# We add population counts to our data and assign each county to the 
# corresponding county set.

COVIDYearlyDataComplete <- COVIDYearlyDataComplete %>% 
  left_join(popDataYearly, by = c('FIPSCode','year')) %>%
  left_join(countySets,by=c('FIPSCode')) %>%
  left_join(states, by = c('stateFIPS')) %>%
  left_join(census_divisions,by='state')

COVIDYearlyDataComplete <- COVIDYearlyDataComplete %>%
  group_by(FIPSCode,countyName,csCode,csName,stateFIPS,state,census_division,year) %>%
  summarize(COVIDDeaths = sum(COVIDDeaths),
            imputedCOVIDDeaths = sum(imputedCOVIDDeaths),
            pop = mean(pop)) %>%
  ungroup()

```

```{r, echo=F}

# Computing overall distribution of deaths by month

monthWeights <- ACDataComplete %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  select(month,monthWeight)

monthWeights <- monthWeights %>% pull(monthWeight)

```

```{r}

# This is to adjust the imputation number for 2022 where it should
# correspond to the first two months and not the full year.

ACYearlyDataComplete <- ACYearlyDataComplete %>%
  mutate(imputedDeaths = if_else(year==202 & is.na(deaths),
                                 imputedDeaths*sum(monthWeights[1:2]),
                                 imputedDeaths))

ACDataComplete <- ACDataComplete %>%
  filter(!(year == 2022 & month > 2))

```

```{r}

yearlyDeaths <- ACYearlyDataComplete %>% filter(year>2014) %>% pull(imputedDeaths)
yearlyDeathsAug <- yearlyDeaths[rep(1:length(yearlyDeaths), each = 12)]
yearlyDeathsAug <- yearlyDeathsAug[as.vector(sapply(1:3127,function(x) (1:86)+(96*(x-1))))]

monthWeights2022 <- monthWeights[1:2]/sum(monthWeights[1:2])
  
monthWeightsAug <- rep(c(rep(monthWeights,7),monthWeights2022),length(FIPSCodes))

yearlyDeathsAug <- yearlyDeathsAug*monthWeightsAug

```

```{r}

ACDataComplete <- ACDataComplete %>%
  mutate(imputedDeaths = if_else(is.na(deaths),yearlyDeathsAug,as.double(deaths))) %>%
  filter(!(year == 2022 & month > 2))

```

```{r}

ACDataYearly <- ACDataComplete %>%
  filter(year<2020) %>%
  group_by(FIPSCode,year) %>%
  summarize(deaths = sum(deaths,na.rm = T)) %>%
  ungroup() %>%
  rename(deathsMonthly=deaths)

suppressionData <- ACYearlyDataComplete %>%
  filter(between(year,2015,2019)) %>%
  left_join(ACDataYearly,by=c('FIPSCode','year')) %>%
  group_by(FIPSCode) %>%
  summarize(deathsDiffAbs = max(imputedDeaths-deathsMonthly,na.rm=T),
            deathsDiffPct = deathsDiffAbs/mean(imputedDeaths,na.rm=T),
            across(c(imputedDeaths,deathsMonthly), ~ sum(.x,na.rm=T))) %>%
  ungroup() %>%
  select(FIPSCode,
         deathsTotal=imputedDeaths,
         deathsTotalMonthly=deathsMonthly,
         deathsDiffAbs,
         deathsDiffPct)

```

```{r, echo=F}

suppressionData %>%
  write_csv(file=here::here(outDir,'suppressionData.csv'))

```

```{r}

# We save all the data so that we do not have to repeat this set of 
# operations each time

arrow::write_feather(popData, here::here(outDir,'popDataMonthlyAlt.feather'))
arrow::write_feather(popDataYearly, here::here(outDir,'popDataYearly.feather'))
arrow::write_feather(ACDataComplete, here::here(outDir,'ACData.feather'))
arrow::write_feather(ACYearlyDataComplete, here::here(outDir,'ACYearlyData.feather'))
arrow::write_feather(COVIDMonthlyDataComplete, here::here(outDir,'COVIDMonthlyData.feather'))
arrow::write_feather(COVIDPeriodsDataComplete, here::here(outDir,'COVIDPeriodsData.feather'))
arrow::write_feather(COVIDYearlyDataComplete, here::here(outDir,'COVIDYearlyData.feather'))

```
