---
title: "Predictors of Excess Mortality"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(glmnet)
library(INLA)
library(lubridate)
library(lme4)
library(here)
library(patchwork)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

# Setting working directories

rm(list=ls())

here::i_am('R/determinants.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

set.seed(42)

```

```{r, echo=F, message=F, warning=F}

# Reading data

covariates <- read_csv(here::here(inDir,'covariates','excess_cov_ahyoung.csv'))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
load(here::here(outDir,'finalSimsFIPS.RData'))

```

```{r, echo=F, message=F, warning=F}

# Reading data

covariates <- covariates %>%
  select(FIPSCode,
         Completeness_pct:Booster_Doses_Vax_Pct,
         poor_or_fair_health:hospitalization_rate) %>%
  mutate(FIPSCode = if_else(FIPSCode < 10000, paste0('0',FIPSCode),paste0(FIPSCode))) %>%
  mutate(across(Completeness_pct:hospitalization_rate, 
                ~ (.x - mean(.x,na.rm=T))/sd(.x,na.rm=T)))

```

```{r, echo=F, message=F, warning=F}

# Reading data

finalSimsFIPS <- finalSimsFIPS %>%
  left_join(popDataYearly,by=c('FIPSCode','year')) %>%
  mutate(excDeathRate = (excDeaths/pop)*100000,
         excDeathRateNorm = (excDeathRate-mean(excDeathRate))/sd(excDeathRate),
         COVIDDeathRate = (COVIDDeaths/pop)*100000,
         COVIDDeathRateNorm = (COVIDDeathRate-mean(COVIDDeathRate))/sd(COVIDDeathRate)) %>%
  left_join(covariates,by=c('FIPSCode'))

```

```{r, echo=F, message=F, warning=F}

indepVars <- finalSimsFIPS %>%
  select(Booster_Doses_Vax_Pct:hospitalization_rate) %>%
  names()

```

```{r, echo=F, message=F, warning=F}

coef_matrix <- function(data,modelFormula,indepVars,year) {
  
  simNames <- unique(data$simNum)

  coefMatrix <- matrix(NA,ncol=length(indepVars) + 1,nrow=length(simNames))
  seMatrix <- matrix(NA,ncol=length(indepVars) + 1,nrow=length(simNames))
  
  i <- 1
  progBar <- txtProgressBar(max=length(simNames),styl=3)
  
  for (thisSimNum in simNames) {
    
    model <- data %>%
    filter(year == year,
           simNum == thisSimNum) %>%
    lm(modelFormula, data = .)
  
    coefMatrix[i,] <- as.numeric(coef(model))
    seMatrix[i,] <- as.numeric(summary(model)$coefficients[,'Std. Error'])
    
    setTxtProgressBar(progBar,i)
    
    i <- i + 1
    
  }
  
  return(list(means = coefMatrix, ses = seMatrix))
  
}

lm_coefs <- function(data,modelFormula,year) {
  
  modelNaive <- data %>%
    drop_na() %>%
    filter(year == year) %>%
    group_by(FIPSCode) %>%
    summarise(across(excDeathRateNorm:hospitalization_rate, ~ mean(.x))) %>%
    lm(modelFormula, data=.)
  
  coefMeansNaive <- as.numeric(coef(modelNaive))[-1]
  coefSesNaive <- as.numeric(summary(modelNaive)$coefficients[-1,'Std. Error'])
  
  return(matrix(c(coefMeansNaive,coefSesNaive),nrow=length(coefMeansNaive),ncol=2))
  
}

coef_summary <- function(data,year,indepVars,depVar) {
  
  indepVarsNames <- sapply(indepVars,
                           function(x) 
                            stringi::stri_trans_totitle(str_replace_all(x,'_',' ')))
  
  modelFormula <- as.formula(paste(c(paste0(depVar,' ~ 1'),
                                     indepVars),
                                   collapse=' + '))
  
  coefMatrices <- coef_matrix(data,modelFormula,indepVars,year=year)

  coefSims <- apply(coefMatrices[['ses']][,-1],M=2,function(x) rnorm(length(x),0,x))
  coefSims <- coefSims + coefMatrices[['means']][,-1] # To set the correct means
  
  coefMeans <- apply(coefSims,M=2,function(x) mean(x))
  coefSes <- apply(coefSims,M=2,function(x) sd(x))
  
  coefData <- matrix(c(coefMeans,coefSes),nrow=length(indepVars),ncol=2)
  coefDataNaive <- lm_coefs(data,modelFormula,year=year)
  
  coefData <- rbind(coefData,coefDataNaive)
  colnames(coefData) <- c('mean','se')
  coefData <- as_tibble(coefData)
  
  coefData <- coefData %>%
    mutate(name = rep(indepVarsNames,2),
           type = rep(c('Simulated','Naive'),each=length(indepVarsNames)))
  
  return(coefData)
  
}
  
```

```{r}

i <- 1

for (year in c(2020,2021)) {
  
  for (depVar in c('excDeathRateNorm','COVIDDeathRateNorm')) {
    
    thisCoefData <- coef_summary(finalSimsFIPS,indepVars,depVar,year=year)
    thisCoefData <- thisCoefData %>%
      mutate(year = year,
             depVar = depVar)
    
    if (i == 1) {
      
      coefData <- thisCoefData      
      
    } else {
      
      coefData <- rbind(coefData,thisCoefData) 
      
    }
    
    i <- i +1
    
  }
}

coefData <- coefData %>%
  mutate(depVar = if_else(depVar == 'excDeathRateNorm',
                          'Excess Death Rate',
                          'COVID Death Rate'))

```

```{r}

coefPlots <- coefData %>%
  filter(!(type=='Simulated' & depVar=='COVID Death Rate')) %>%
ggplot() +
  geom_point(mapping=aes(x=mean,y=name,color=type)) +
  geom_errorbarh(mapping=aes(xmin=mean - 1.96*se,
                             xmax=mean + 1.96*se,
                             y=name,
                             color=type)) +
  coord_cartesian(xlim=c(-0.3,0.25)) +
  geom_vline(xintercept = 0) +
  facet_grid(rows=vars(depVar),vars(cols=year)) + 
  labs(x='Coefficient Magnitude',
       y='',
       color='') +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```

```{r}

pdf(here::here('figures','coefPlots.pdf'), width=12, height = 10)

coefPlots

dev.off()

```

```{r}

coefPlot2020 <- ggplot() +
  geom_point(mapping=aes(x=coefMeans2020,y=depVarsNames,color='Simulated')) +
  geom_errorbarh(mapping=aes(xmin=coefMeans2020 - 1.96*coefSes2020,
                             xmax=coefMeans2020 + 1.96*coefSes2020,
                             y=depVarsNames,
                             color='Simulated')) +
  geom_point(mapping=aes(x=coefMeansNaive2020,y=depVarsNames,color='Naive')) +
  geom_errorbarh(mapping=aes(xmin=coefMeansNaive2020 - 1.96*coefSesNaive2020,
                             xmax=coefMeansNaive2020 + 1.96*coefSesNaive2020,
                             y=depVarsNames,
                             color='Naive')) +
  coord_cartesian(xlim=c(-0.3,0.25)) +
  geom_vline(xintercept = 0) +
  labs(x='Coefficient Magnitude',
       y='',
       color='') +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```

```{r, echo=F, message=F, warning=F}

dataMatrix2021 <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year == 2021) %>%
  group_by(FIPSCode) %>%
  summarise(across(excDeathsRateNorm:hospitalization_rate, ~ mean(.x)))

```

```{r, echo=F, message=F, warning=F}

coefMatrix2021 <- matrix(NA,ncol=length(depVars) + 1,nrow=1000)
seMatrix2021 <- matrix(NA,ncol=length(depVars) + 1,nrow=1000)

i <- 1
progBar <- txtProgressBar(max=1000,styl=3)

for (thisSimNum in unique(finalSimsFIPS$simNum)) {
  
  model <- finalSimsFIPS %>%
  filter(year == 2021,
         simNum == thisSimNum) %>%
  lm(modelFormula, data = .)

  coefMatrix2021[i,] <- as.numeric(coef(model))
  seMatrix2021[i,] <- as.numeric(summary(model)$coefficients[,'Std. Error'])
  
  setTxtProgressBar(progBar,i)
  
  i <- i + 1
  
}

```

```{r}

coefSims2021 <- apply(seMatrix2021[,-1],M=2,function(x) rnorm(length(x),0,x))
coefSims2021 <- coefSims2021 + coefMatrix2021[,-1] # To set the correct means

coefMeans2021 <- apply(coefSims2021,M=2,function(x) mean(x))
coefSes2021 <- apply(coefSims2021,M=2,function(x) sd(x))

modelNaive <- lm(modelFormula, data=dataMatrix2021)
coefMeansNaive2021 <- as.numeric(coef(modelNaive))[-1]
coefSesNaive2021 <- as.numeric(summary(modelNaive)$coefficients[-1,'Std. Error'])

depVarsNames <- sapply(depVars,
                       function(x) stringi::stri_trans_totitle(str_replace_all(x,'_',' ')))

coefPlot2021 <- ggplot() +
  geom_point(mapping=aes(x=coefMeans2021,y=depVarsNames,color='Simulated')) +
  geom_errorbarh(mapping=aes(xmin=coefMeans2021 - 1.96*coefSes2021,
                             xmax=coefMeans2021 + 1.96*coefSes2021,
                             y=depVarsNames,
                             color='Simulated')) +
  geom_point(mapping=aes(x=coefMeansNaive2021,y=depVarsNames,color='Naive')) +
  geom_errorbarh(mapping=aes(xmin=coefMeansNaive2021 - 1.96*coefSesNaive2021,
                             xmax=coefMeansNaive2021 + 1.96*coefSesNaive2021,
                             y=depVarsNames,
                             color='Naive')) +
  geom_vline(xintercept = 0) +
  coord_cartesian(xlim=c(-0.3,0.25)) +
  labs(x='Coefficient Magnitude',
       y='',
       color='') +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```

```{r}

coefPlot2020 + coefPlot2021 + plot_layout(guides='collect')

```



```{r, eval=F}

X <- model.matrix(modelFormula,data=dataMatrix2020)
y <- dataMatrix2020 %>% pull(excDeathsRateNorm)

cv_model <- cv.glmnet(X, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min

#find coefficients of best model
best_model <- glmnet(X, y, alpha = 1, lambda = best_lambda)
best_model$beta

```

```{r}

start.time <- Sys.time()
modelNaiveStan <- stan_lm(modelFormula, data=dataMatrix,prior= R2(location = 0.5))
end.time <- Sys.time()
time.taken <- end.time - start.time
print(time.taken)

```

```{r}

samples <- extract(modelNaiveStan)

```


```{r}

model <- finalSimsFIPS %>%
  filter(year == 2020) %>% 
  group_by(FIPSCode) %>%
  summarise(excDeathsNorm = mean(excDeathsNorm),
            Booster_Doses_Vax_Pct = mean(Booster_Doses_Vax_Pct)) %>%
  ungroup() %>%
  lm(excDeathsNorm ~ 1 + Booster_Doses_Vax_Pct, data = .)

summary(model)

```

```{r}

finalSimsFIPS %>%
filter(year == 2020,
       simNum %in% sapply(1:100,function(x) paste0('V',x))) %>%
ggplot() +
  geom_smooth(mapping=aes(x=Booster_Doses_Vax_Pct,y=excDeathsNorm,group=simNum),
              method='lm',se=F,alpha=0.1)


```


```{r}

beta.post.samp <- rnorm(1000,mean=coefMatrix[,2],sd=seMatrix[,2])
quantile(beta.post.samp,probs=c(0.025,0.5,0.975))

```




```{r}

model <- finalSimsFIPS %>%
filter(year == 2020,
       simNum %in% sapply(1:10,function(x) paste0('V',x))) %>%
inla(excDeaths ~ 1 + Booster_Doses_Vax_Pct + f(simNum, Booster_Doses_Vax_Pct, model="iid"), 
     data = .)

summary(model)

```

```{r}

x <- rnorm(1000)
ymeans <- 3 + x*2 + rnorm(1000)

coefMatrix <- matrix(NA,ncol=2,nrow=1000)
progBar <- txtProgressBar(max=1000,styl=3)

for (i in 1:1000) {

  y <- rnorm(1000,ymeans,10b)

  model <- lm(y ~ 1 + x)

  coefMatrix[i,] <- as.numeric(coef(model))
  
  setTxtProgressBar(progBar,i)
  
  i <- i + 1
  
}

print(apply(coefMatrix,M=2,function(x) mean(x)))
print(apply(coefMatrix,M=2,function(x) sd(x)))
summary(lm(ymeans ~ 1 + x))

```

```{r}

a <- 5
b <- 1

star.x <- (a-1)/b 
star.sigma2 <- (a-1)/b^2

x <- seq(0,20,length.out=100)

par(mfrow = c(1, 2)) 
plot(x,dgamma(x,a,b),type='l',
     ylab='',xlab='Gamma(5,1)')
lines(x,dnorm(x,star.x,sqrt(star.sigma2)),col='red')

a <- 3
b <- 1

star.x <- (a-1)/b 
star.sigma2 <- (a-1)/b^2

x <- seq(0,20,length.out=100)

plot(x,dgamma(x,a,b),type='l',
     ylab='',xlab='Gamma(3,1)')
lines(x,dnorm(x,star.x,sqrt(star.sigma2)),col='red')

```


