---
title: "Estimates of Excess Deaths by Wave"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(lubridate)
library(INLA)
library(knitr)
library(here)
library(ggthemes)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/estimatesWaves.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```


```{r, echo=F, message=F, warning=F}

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))
COVIDYearlyData <- tibble(arrow::read_feather(here::here(outDir,'COVIDYearlyData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
countySets <- tibble(arrow::read_feather(here::here(outDir,'countySetsFinal.feather')))
states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r}

ACData <- ACData %>%
  mutate(monthYear = make_date(year=year,month=month,day=1)) %>%
  mutate(period = case_when(
           between(monthYear,
                   make_date(2020,3,1),
                   make_date(2020,8,1)) ~ 'Initial Wave (Mar-Aug 2020)',
           between(monthYear,
                   make_date(2020,10,1),
                   make_date(2021,2,1)) ~ 'Winter Wave (Oct 2021 - Feb 2020)',
           between(monthYear,
                   make_date(2021,8,1),
                   make_date(2021,10,1)) ~ 'Delta (Aug-Oct 2021)',
           between(monthYear,
                   make_date(2021,11,1),
                   make_date(2022,2,1)) ~ 'Omicron (Nov 2021 - Feb 2022)',
           TRUE ~ 'Non Peak'))

```

```{r}

ACPeriodData <- ACData %>%
  group_by(FIPSCode,state,stateFIPS,period) %>%
  summarise(imputedDeaths = sum(imputedDeaths),
            pop = mean(pop)) %>%
  ungroup()

```

```{r, echo=F}

# We load the pre-trained models

load(here::here('R','RObjects','simMonthly.RData'))
load(here::here('R','RObjects','simYearlySimple.RData'))

```

```{r}

simulationsMonthly <- as_tibble(t(death.draws))

simulationsMonthly <- simulationsMonthly %>% 
  mutate(year = ACData %>% pull(year),
         month = ACData %>% pull(month),
         monthYear = make_date(year=year,month=month,day=1),
         period = ACData %>% pull(period),
         FIPSCode = ACData %>% pull(FIPSCode),
         stateFIPS = ACData %>% pull(stateFIPS),
         pop = ACData %>% pull(pop)) %>%
  relocate(FIPSCode,stateFIPS,year,month,monthYear,period,pop)

```

```{r}

firstMonth <- 3
lastMonth <- 2

simulationsFIPSMonthly <- simulationsMonthly %>%
  filter(between(monthYear,make_date(2020,3,1),make_date(2022,2,1))) %>%
  group_by(period,FIPSCode,stateFIPS) %>%
  summarize(across(V1:V1000, ~ sum(.x))) %>%
  ungroup() %>%
  left_join(ACPeriodData,by=c('FIPSCode','stateFIPS','period'))

simulationsFIPSMonthly <- simulationsFIPSMonthly %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  group_by(period,FIPSCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            probPositive = sum(imputedDeaths-expDeaths>0)/n(),
            imputedDeaths = mean(imputedDeaths))

```


```{r, echo=F}

# Computing overall distribution of deaths by month

monthWeights <- ACData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  select(month,monthWeight)

monthWeights <- monthWeights %>% pull(monthWeight)

```

```{r}

n.sim <- 1000
years <- 2015:2022
FIPSCodes <- as.numeric(unique(ACData$FIPSCode))

death.draws.y.partial <- t(death.draws.y[,pull(ACYearlyData,year)>=2015])

death.draws.y.aug <- death.draws.y.partial[rep(1:nrow(death.draws.y.partial), each = 12), ]
  
monthWeights.matrix <- as.matrix(rep(monthWeights,length(years)*length(FIPSCodes)))
monthWeights.matrix <- monthWeights.matrix[, rep(1,n.sim)]

death.draws.y.aug <- death.draws.y.aug*monthWeights.matrix

death.draws.y.aug <- death.draws.y.aug[as.vector(sapply(1:3127,function(x) (1:86)+(96*(x-1)))),]

rm(death.draws.y.partial,
   monthWeights.matrix)

```

```{r}

simulationsYearly <- as_tibble(death.draws.y.aug)

simulationsYearly <- simulationsYearly %>% 
  mutate(year = ACData %>% pull(year),
         month = ACData %>% pull(month),
         monthYear = make_date(year=year,month=month,day=1),
         period = ACData %>% pull(period),
         FIPSCode = ACData %>% pull(FIPSCode),
         stateFIPS = ACData %>% pull(stateFIPS),
         pop = ACData %>% pull(pop)) %>%
  relocate(FIPSCode,stateFIPS,year,month,monthYear,period,pop)

```

```{r}

simulationsFIPSYearly <- simulationsYearly %>%
  filter(between(monthYear,make_date(2020,3,1),make_date(2022,2,1))) %>%
  group_by(period,FIPSCode,stateFIPS) %>%
  summarize(across(V1:V1000, ~ sum(.x))) %>%
  ungroup() %>%
  left_join(ACPeriodData,by=c('FIPSCode','stateFIPS','period'))

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  group_by(period,FIPSCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            probPositive = sum(imputedDeaths-expDeaths>0)/n(),
            imputedDeaths = mean(imputedDeaths))

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  rename_with(~ paste0(.x,'SC'), expDeathsLow:imputedDeaths)

```

```{r, echo=F}

suppressionData <- read_csv(here::here(outDir,'suppressionData.csv'))
  
```

```{r, echo=F}

# We set which estimate to used based on the relative average error of the 

diffTreshold <- 0.05

finalSimsFIPS <- simulationsFIPSMonthly  %>%
  left_join(simulationsFIPSYearly,by=c('FIPSCode','stateFIPS','period')) %>%
  left_join(suppressionData,by='FIPSCode') %>%
  mutate(deathsDiffPct = if_else(is.na(deathsDiffPct),0,deathsDiffPct),
         expDeathsMed = if_else(deathsDiffPct>diffTreshold,expDeathsMedSC,expDeathsMed),
         expDeathsLow = if_else(deathsDiffPct>diffTreshold,expDeathsLowSC,expDeathsLow),
         expDeathsUp = if_else(deathsDiffPct>diffTreshold,expDeathsUpSC,expDeathsUp),
         imputedDeaths = if_else(deathsDiffPct>diffTreshold,imputedDeathsSC,imputedDeaths),
         probPositive = if_else(deathsDiffPct>diffTreshold,probPositiveSC,probPositive)) %>%
  select(FIPSCode,stateFIPS,period,
         expDeathsLow:expDeathsUp,imputedDeaths,probPositive)

```

```{r, echo=FALSE, warning=F, message=F}

## Metropolitan status
metro <- read_csv(here::here(inDir,'utilities','FIPSmetroregion4cat.csv'))
metro <- metro %>%
  select(FIPSCode = fips,
         metroCat = metroname) %>%
  mutate(FIPSCode = if_else(nchar(FIPSCode)<5,paste0('0',FIPSCode),as.character(FIPSCode)),
         metroCat = case_when(metroCat == 'Nonmetro' ~ 'Non Metro',
                               metroCat == 'Md/Sm metro' ~ 'Medium or Small Metro',
                               metroCat == 'Lg fringe metro' ~ 'Large Fringe Metro' ,
                               metroCat == 'Lg central metro' ~ 'Large Central Metro'))
  

finalSimsFIPS <- finalSimsFIPS %>%
  left_join(metro, by = 'FIPSCode')

```

```{r, echo=FALSE, warning=F, message=F}

## BEA regions
BEARegions <- read_rds(here::here(inDir,'utilities','stateBEARegionCrosswalk.rds'))
BEARegions <- BEARegions %>%
  select(stateStr = state_abb,
         BEARegion = region_bea)

finalSimsFIPS <- finalSimsFIPS %>%
  left_join(states,by = c('stateFIPS')) %>%
  left_join(BEARegions, by = 'stateStr')

```

```{r, echo=FALSE, warning=F, message=F}

addNonMetro <- c('02068','02105','02198','02230','02275','02282', 
                 '02013','02016','02164','02270','46113','02130',
                 '02188','02290','04012','30067')

addLgFringeMetro <- c('08001','08014')
addMdSmMetro <- c('08013','08123','51515')

## fill out missing metro
finalSimsFIPS <- finalSimsFIPS %>%
  mutate(metroCat = case_when(FIPSCode %in% addNonMetro ~ "Non Metro",
                              FIPSCode %in% addLgFringeMetro ~ 'Large Fringe Metro',
                              FIPSCode %in% addMdSmMetro ~ 'Medium or Small Metro',
                              TRUE ~ metroCat))

```

```{r, echo=FALSE, warning=F, message=F}

finalSimsFIPS <- finalSimsFIPS %>%
  mutate(excDeathsMed = imputedDeaths - expDeathsMed,
         excDeathsLow = imputedDeaths - expDeathsUp,
         excDeathsUp = imputedDeaths - expDeathsLow)

```

```{r, echo=FALSE, warning=F, message=F}

finalSimsFIPS %>% write_csv(here::here(outDir,'exMortEstimatesWavesINLA.csv'))

```