---
title: "Estimates of Yearly Excess Deaths"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(INLA)
library(lubridate)
library(here)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

# Setting working directories

rm(list=ls())

here::i_am('R/estimatesYearly.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

set.seed(42)

```

```{r, echo=F, message=F, warning=F}

# Reading data

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))
COVIDYearlyData <- tibble(arrow::read_feather(here::here(outDir,'COVIDYearlyData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
countySets <- tibble(arrow::read_feather(here::here(outDir,'countySetsFinal.feather')))
states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r, echo=F}

# We load the pre-trained models

load(here::here('R','RObjects','simMonthly.RData'))

```

```{r}

simDataMonthly <- ACData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id(),
         FIPSCode2 = FIPSCode) %>%
  ungroup() %>%
  group_by(year,month) %>%
  mutate(timeID = cur_group_id()) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(yearID = cur_group_id()) %>%
  ungroup() %>%
  mutate(CDR = if_else(year>2019,NA_real_,CDR),
         deathsCensored = if_else(year>2019,NA_integer_,deaths)) %>%
  arrange(FIPSCode,year,month)

```

```{r}

n.sim <- 1000

mean.deaths <- apply(death.draws,M=2,function(x) mean(x))
up.deaths <- apply(death.draws,M=2,function(x) quantile(x,0.95))
low.deaths <- apply(death.draws,M=2,function(x) quantile(x,0.05))

```

```{r}

testData <- tibble(deaths = pull(ACData,deaths),
                   CDR = pull(ACData,CDR),
                   pop = pull(ACData,pop),
                   FIPSCode = pull(ACData,FIPSCode),
                   year = pull(ACData,year),
                   month = pull(ACData,month))

testData <- testData %>%
  mutate(expDeathsMean = mean.deaths,
         expDeathsUp = up.deaths,
         expDeathsLow = low.deaths,
         monthYear = make_date(year,month,1))

```

```{r}

# Good for overfitting: c(12,15,21,47,86,13)
# Good for trend: c(1,17,63,71,75,91)
# Hard to predict: 37,64
# To examine: c(85)

# Examples: c(1,58,89,93)

numFIPS <- length(unique(pull(ACData,FIPSCode)))

testFigure <- testData %>%
  filter(FIPSCode %in% sample(unique(pull(ACData,FIPSCode)),6)) %>%
  ggplot() +
  geom_line(mapping=aes(x=monthYear,y=deaths/pop,color='Observed')) +
  geom_line(mapping=aes(x=monthYear,y=expDeathsMean/pop,color='Expected')) +
  geom_ribbon(mapping=aes(x=monthYear,ymin=expDeathsLow/pop,ymax=expDeathsUp/pop,
                          fill='Expected'),alpha=0.3) +
  labs(x='Deaths',
       y='',
       color='',
       fill='') +
  facet_wrap(~FIPSCode) +
  guides(fill='none')

testFigure

```

```{r}

simulationsMonthly <- as_tibble(t(death.draws))

simulationsMonthly <- simulationsMonthly %>% 
  mutate(year = ACData %>% pull(year),
         month = ACData %>% pull(month),
         monthYear = make_date(year=year,month=month,day=1),
         FIPSCode = ACData %>% pull(FIPSCode),
         csCode = ACData %>% pull(csCode),
         stateFIPS = ACData %>% pull(stateFIPS),
         pop = ACData %>% pull(pop)) %>%
  relocate(FIPSCode,csCode,stateFIPS,year,month,monthYear,pop)

```

```{r}

firstMonth <- 3
lastMonth <- 2

simulationsFIPSMonthly <- simulationsMonthly %>%
  filter(monthYear >= make_date(2020,firstMonth,1),
         monthYear <= make_date(2022,lastMonth,1)) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(across(V1:V1000, ~ sum(.x))) %>%
  ungroup() 

simulationsFIPSMonthly <- simulationsFIPSMonthly %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','stateFIPS','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths,
         nonCOVIDexcess = excDeaths-imputedCOVIDDeaths) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            nonCovidExcCDRLow = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.05)),
            nonCovidExcCDRMed = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.5)),
            nonCovidExcCDRUp = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.95)),
            COVIDExcRatio = quantile(imputedCOVIDDeaths/excDeaths,probs=c(0.5),na.rm=T))

```

```{r, echo=F}

# We load the pre-trained models

load(here::here('R','RObjects','simYearlySimple.RData'))

```

```{r, echo=F}

# Computing overall distribution of deaths by month

monthWeights <- ACData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  select(month,monthWeight)

monthWeights <- monthWeights %>% pull(monthWeight)

```

```{r}

simDataYearly <- ACYearlyData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id(),
         FIPSCode2 = FIPSCode) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(yearID = cur_group_id()) %>%
  ungroup() %>%
  mutate(CDR = if_else(year>2019,NA_real_,CDR),
         deathsCensored = if_else(year>2019,NA_integer_,deaths)) %>%
  arrange(FIPSCode,year)

```

```{r}

simulationsYearly <- as_tibble(t(death.draws.y))

simulationsYearly <- simulationsYearly %>% 
  mutate(year = ACYearlyData %>% pull(year),
         FIPSCode = ACYearlyData %>% pull(FIPSCode),
         csCode = ACYearlyData %>% pull(csCode),
         stateFIPS = ACYearlyData %>% pull(stateFIPS),
         pop = ACYearlyData %>% pull(pop))

```

```{r}

simulationsFIPSYearly <- simulationsYearly %>%
  filter(year >= 2020,
         year <= 2022)

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  mutate(across(V1:V1000, ~ case_when(year == 2020 ~ .x*sum(monthWeights[firstMonth:12]),
                                      year == 2021 ~ .x*1,
                                      year == 2022 ~ .x*sum(monthWeights[1:lastMonth])))) %>%
  select(-pop)

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','stateFIPS','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths,
         nonCOVIDexcess = excDeaths-imputedCOVIDDeaths) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            nonCovidExcCDRLow = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.05)),
            nonCovidExcCDRMed = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.5)),
            nonCovidExcCDRUp = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.95)),
            COVIDExcRatio = quantile(imputedCOVIDDeaths/excDeaths,probs=c(0.5),na.rm=T))

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  rename_with(~ paste0(.x,'SC'), expDeathsLow:COVIDExcRatio)

```

```{r, echo=F}

suppressionData <- read_csv(here::here(outDir,'suppressionData.csv'))
  
```

```{r, echo=F}

# We set which estimate to used based on the relative average error of the 

diffTreshold <- 0.05

finalSimsFIPS <- simulationsFIPSMonthly  %>%
  left_join(simulationsFIPSYearly,by=c('csCode','FIPSCode','year')) %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  left_join(suppressionData,by='FIPSCode') %>%
  mutate(deathsDiffPct = if_else(is.na(deathsDiffPct),0,deathsDiffPct),
         expDeathsMed = if_else(deathsDiffPct>diffTreshold,expDeathsMedSC,expDeathsMed),
         expDeathsLow = if_else(deathsDiffPct>diffTreshold,expDeathsLowSC,expDeathsLow),
         expDeathsUp = if_else(deathsDiffPct>diffTreshold,expDeathsUpSC,expDeathsUp),
         excDeathsMed = if_else(deathsDiffPct>diffTreshold,excDeathsMedSC,excDeathsMed),
         excDeathsLow = if_else(deathsDiffPct>diffTreshold,excDeathsLowSC,excDeathsLow),
         excDeathsUp = if_else(deathsDiffPct>diffTreshold,excDeathsUpSC,excDeathsUp),
         nonCovidExcCDRMed = if_else(deathsDiffPct>diffTreshold,nonCovidExcCDRMedSC,nonCovidExcCDRMed),
         nonCovidExcCDRLow = if_else(deathsDiffPct>diffTreshold,nonCovidExcCDRLowSC,nonCovidExcCDRLow),
         nonCovidExcCDRUp = if_else(deathsDiffPct>diffTreshold,nonCovidExcCDRUpSC,nonCovidExcCDRUp),
         COVIDExcRatio = if_else(deathsDiffPct>diffTreshold,COVIDExcRatioSC,COVIDExcRatio)) %>%
  select(csCode,FIPSCode,year,
         expDeathsLow,expDeathsMed,expDeathsUp,
         imputedDeaths,
         excDeathsLow,excDeathsMed,excDeathsUp,
         imputedCOVIDDeaths,
         nonCovidExcCDRLow,nonCovidExcCDRMed,nonCovidExcCDRUp,
         COVIDExcRatio)

```

```{r, echo=FALSE, message=F, warning=F}

finalSimsFIPS <- finalSimsFIPS %>%
  mutate(expDeathsLow = round(expDeathsLow),
         expDeathsMed = round(expDeathsMed),
         expDeathsUp = round(expDeathsUp),
         excDeathsLow = round(excDeathsLow),
         excDeathsMed = round(excDeathsMed),
         excDeathsUp = round(excDeathsUp)) %>%
  rename(deaths = imputedDeaths,
         COVIDDeaths = imputedCOVIDDeaths)
  
```

```{r, echo=FALSE, message=F, warning=F}

adjF2020 = (13-firstMonth)/12
adjF2022 = lastMonth/12

excDeaths2020 <- finalSimsFIPS %>%
  ungroup() %>%
  filter(year == 2020) %>%
  select(FIPSCode,csCode,
         expDeathsLow,expDeathsMed,expDeathsUp,
         deaths,
         excDeathsLow,excDeathsMed,excDeathsUp,
         COVIDDeaths,
         nonCovidExcCDRLow,nonCovidExcCDRMed,nonCovidExcCDRUp,
         COVIDExcRatio) %>%
  mutate(nonCovidExcCDRLow = nonCovidExcCDRLow/adjF2020,
         nonCovidExcCDRMed = nonCovidExcCDRMed/adjF2020,
         nonCovidExcCDRUp = nonCovidExcCDRUp/adjF2020) %>%
  rename_with(~ paste0(.x,'2020'),expDeathsLow:COVIDExcRatio)

excDeaths2021 <- finalSimsFIPS %>%
  ungroup() %>%
  filter(year == 2021) %>%
  select(FIPSCode,csCode,
         expDeathsLow,expDeathsMed,expDeathsUp,
         deaths,
         excDeathsLow,excDeathsMed,excDeathsUp,
         COVIDDeaths,
         nonCovidExcCDRLow,nonCovidExcCDRMed,nonCovidExcCDRUp,
         COVIDExcRatio) %>%
  rename_with(~ paste0(.x,'2021'),expDeathsLow:COVIDExcRatio)

excDeaths2022 <- finalSimsFIPS %>%
  ungroup() %>%
  filter(year == 2022) %>%
  select(FIPSCode,csCode,
         expDeathsLow,expDeathsMed,expDeathsUp,
         deaths,
         excDeathsLow,excDeathsMed,excDeathsUp,
         COVIDDeaths,
         nonCovidExcCDRLow,nonCovidExcCDRMed,nonCovidExcCDRUp,
         COVIDExcRatio) %>%
  mutate(nonCovidExcCDRLow = nonCovidExcCDRLow,
         nonCovidExcCDRMed = nonCovidExcCDRMed,
         nonCovidExcCDRUp = nonCovidExcCDRUp) %>%
  rename_with(~ paste0(.x,'2022'),expDeathsLow:COVIDExcRatio)

excDeaths <- excDeaths2020 %>%
  left_join(excDeaths2021,by=c('FIPSCode','csCode')) %>%  
  left_join(excDeaths2022,by=c('FIPSCode','csCode')) %>%
  left_join(select(filter(popDataYearly,year==2020),-year),by=c('FIPSCode')) %>%
  rename(pop2020=pop) %>%
  left_join(select(filter(popDataYearly,year==2021),-year),by=c('FIPSCode')) %>%
  rename(pop2021=pop) %>%
  left_join(select(filter(popDataYearly,year==2022),-year),by=c('FIPSCode')) %>%
  rename(pop2022=pop) %>%
  mutate(pop2020 = round(pop2020),
         pop2021 = round(pop2021),
         pop2022 = round(pop2022)) %>%
  left_join(countySets,by=c('FIPSCode','csCode')) %>%
  left_join(states,by='stateFIPS')

```

```{r, echo=F}

## Basic Checks

sum(excDeaths$excDeathsMed2020)
sum(excDeaths$excDeathsMed2021)
sum(excDeaths$excDeathsMed2022)
sum(excDeaths$COVIDDeaths2020)
sum(excDeaths$COVIDDeaths2021)
sum(excDeaths$COVIDDeaths2022)
sum(excDeaths$COVIDDeaths2020)/sum(excDeaths$excDeathsMed2020)
sum(excDeaths$COVIDDeaths2021)/sum(excDeaths$excDeathsMed2021)
sum(excDeaths$COVIDDeaths2022)/sum(excDeaths$excDeathsMed2022)

```

```{r, echo=F}

excDeaths %>% write_csv(here::here(outDir,'exMortEstimatesINLA.csv'))

```
