---
title: "County-Level Mortality Model - Performance"
author: "Eugenio Paglino"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(tidyverse)
library(lubridate)
library(lme4)
library(matrixStats)
library(patchwork)
library(knitr)
library(here)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/exMortPerformanceAC.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```


```{r, echo=F, message=F, warning=F}

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))
COVIDYearlyData <- tibble(arrow::read_feather(here::here(outDir,'COVIDYearlyData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
countySets <- tibble(arrow::read_feather(here::here(outDir,'countySetsFinal.feather')))
states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r}

ACData <- ACData %>%
  mutate(monthYear = make_date(year=year,month=month,day=1)) 

ACData <- ACData %>% filter(year>2014)

```

```{r, echo=F}

# We load the pre-trained models

load(here::here('R','RObjects','modelBaseLT.RData'))
load(here::here('R','RObjects','modelRandomTimeLT.RData'))
load(here::here('R','RObjects','modelBaseLF.RData'))
load(here::here('R','RObjects','modelRandomTimeLF.RData'))
load(here::here('R','RObjects','modelRandomTimePlusLT.RData'))

```

```{r, echo=FALSE}

# Function to compute the Root Mean Squared Error (RMSE) between two series

RMSE <- function(series1,series2) {
  
  return(sqrt(mean((series1 - series2)^2)))
  
}

# We compute the RMSE for the three models and store the result in a data.frame

RMSEs <- tibble(Performance=c('Training Data (2014-2018)',
                                  'Test Data (2019)',
                                  'Overall'),
                    modelBase=c(RMSE(filter(drop_na(ACData),year<2019)$CDR,
                                     predict(modelBaseLT)),
                                RMSE(filter(drop_na(ACData),year==2019)$CDR,
                                     predict(modelBaseLT,filter(drop_na(ACData),year==2019),
                                             allow.new.levels=T)),
                                RMSE(filter(drop_na(ACData),year<=2019)$CDR,
                                     predict(modelBaseLT,filter(drop_na(ACData),year<=2019),
                                             allow.new.levels=T))),
                    modelRandomTime=c(RMSE(filter(drop_na(ACData),year<2019)$CDR,
                                           predict(modelRandomTimeLT)),
                                      RMSE(filter(drop_na(ACData),year==2019)$CDR,
                                           predict(modelRandomTimeLT,filter(drop_na(ACData),year==2019),
                                                   allow.new.levels=T)),
                                      RMSE(filter(drop_na(ACData),year<=2019)$CDR,
                                           predict(modelRandomTimeLT,filter(drop_na(ACData),year<=2019),
                                                   allow.new.levels=T))))

```

```{r, echo=F}

kable(RMSEs,
      col.names=c('Performance','Base Model','Random Time Model'))

```

```{r simulation, cache=TRUE, echo=F}

# We simulate prediction from the models. Simulating, rather than predicting, 
# allows us to easily get a sense of the uncertainty around our estimates

#set.seed(42)
n.sim = 1000

FIPSCodes <- as.character(unique(ACData$FIPSCode))
numFIPS <- length(FIPSCodes)
lastMonth <- 10
years <- seq(2015,2021)
numYears <- length(years)
numObs <- numYears*12 - (12-lastMonth)

simDataMonthly <- tibble(year=rep(c(rep(years[-numYears],each=12),rep(2021,lastMonth)),numFIPS),
                         month=rep(c(rep(seq(1,12),numYears-1),seq(1,lastMonth)),numFIPS),
                         FIPSCode=rep(rep(FIPSCodes,each=numObs)))

simDataMonthly <- simDataMonthly %>% left_join(countySets, by = c('FIPSCode'))
simDataMonthly <- simDataMonthly %>% left_join(states, by = c('stateFIPS'))
simDataMonthly <- simDataMonthly %>% left_join(popData, by = c('FIPSCode','year','month'))

#simDataMonthly <- simDataMonthly[1:100,]
#simDataMonthly <- filter(simDataMonthly,FIPSCode=='08059')

simDataMonthly <- simDataMonthly %>% 
  mutate(monthYear = make_date(year=year,month=month,day=1),
         CDR = predict(modelRandomTimeLF,newdata=simDataMonthly,allow.new.levels=T),
         expDeaths = (pop/100000)*CDR)

```

```{r}

yearlyData <- simDataMonthly %>% 
  group_by(FIPSCode,year) %>%
  summarise(expDeaths = sum(expDeaths)) %>%
  left_join(dplyr::select(ACYearlyData,FIPSCode,year,deaths),by=c('FIPSCode','year')) %>%
  group_by(FIPSCode) %>%
  summarize(meanExpDeaths = mean(expDeaths,na.rm=T),
            meanDeaths = mean(deaths,na.rm=T),
            meanDifference = abs(meanExpDeaths - meanDeaths)/meanDeaths)

yearlyData %>%
  write_csv(file=here::here(outDir,'problematicFIPSData.csv'))

```


```{r}

# Computing overall distribution of deaths by month

monthWeights <- ACData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  dplyr::select(month,monthWeight)

monthWeights <- as.numeric(monthWeights$monthWeight)

```

```{r simulation, cache=TRUE, echo=F}

# We simulate prediction from the models. Simulating, rather than predicting, 
# allows us to easily get a sense of the uncertainty around our estimates

#set.seed(42)

simDataYearly <- tibble(year=rep(years,numFIPS),
                        FIPSCode=rep(FIPSCodes,each=numYears))

simDataYearly <- simDataYearly %>% left_join(countySets, by = c('FIPSCode'))
simDataYearly <- simDataYearly %>% left_join(states, by = c('stateFIPS'))
simDataYearly <- simDataYearly %>% left_join(popDataYearly, by = c('FIPSCode','year'))

simDataYearly <- simDataYearly %>% drop_na()

#simDataYearly <- simDataYearly[1:100,]

simDataYearly <- simDataYearly %>% 
  mutate(CDR = predict(modelRandomTimeYearlyLF,newdata=simDataYearly,allow.new.levels=T),
         expDeaths = (pop/100000)*CDR) %>%
  ungroup()

# I bet there's a way to set this up in a vectorized way

simDataYearly <- simDataYearly %>%
  mutate(expDeaths1 = expDeaths*monthWeights[1],
         expDeaths2 = expDeaths*monthWeights[2],
         expDeaths3 = expDeaths*monthWeights[3],
         expDeaths4 = expDeaths*monthWeights[4],
         expDeaths5 = expDeaths*monthWeights[5],
         expDeaths6 = expDeaths*monthWeights[6],
         expDeaths7 = expDeaths*monthWeights[7],
         expDeaths8 = expDeaths*monthWeights[8],
         expDeaths9 = expDeaths*monthWeights[9],
         expDeaths10 = expDeaths*monthWeights[10],
         expDeaths11 = expDeaths*monthWeights[11],
         expDeaths12 = expDeaths*monthWeights[12])

simDataYearly <- simDataYearly %>%
  gather(expDeaths1:expDeaths12, key='month', value='expDeaths') %>%
  mutate(month = as.integer(str_sub(month,10,12)),
         monthYear = make_date(year,month,1))

simDataYearly <- simDataYearly %>%
  rename(expDeathsSC = expDeaths)

```

```{r}

problematicFIPSData <- read_csv(here::here(outDir,'problematicFIPSData.csv'),
                                col_types = cols(FIPSCode = col_character(),
                                                 meanDifference = col_double()))
  
```

```{r}

simulations <- simDataMonthly %>%
  left_join(dplyr::select(simDataYearly,FIPSCode,year,month,expDeathsSC),
            by=c('FIPSCode','year','month')) %>%
  left_join(problematicFIPSData,by='FIPSCode') %>%
  left_join(dplyr::select(ACData,FIPSCode,month,year,deaths), 
                                 by = c('FIPSCode','month','year')) %>%
  mutate(meanDifference = if_else(is.na(meanDifference),0,meanDifference),
         expDeaths = if_else(meanDifference>0.1,expDeathsSC,expDeaths),
         monthYear = make_date(year,month,day=1))

```

```{r, echo=F, message=F, warning=F, fig.align='center', fig.cap='Predicting the National Average Monthly CDR', fig.width=8}

# The prediction intervals in this graph are wrong

simulations %>% 
  drop_na(expDeaths,deaths) %>%
  filter(year<2020) %>%
  group_by(monthYear) %>% 
  summarize(expDeaths = sum(expDeaths),
            deaths = sum(deaths)) %>%
  ggplot() +
    geom_line(mapping=aes(x=monthYear,y=deaths,color='Actual')) +
    geom_line(mapping=aes(x=monthYear,y=expDeaths,color='Simulated-RT')) +
    labs(x='Time',
         y='Deaths',
         colour='') +
    theme(legend.position="bottom")

```

```{r, echo=F, eval=F, message=F, warning=F, fig.align='center', fig.width=15, fig.height=8}

# Creating a plot with predicted vs actual rates for each county in groups of
# 12 (ordered by FIPS code.

simulations <- simulations %>%
  mutate(countyNameState = paste(countyName,' (',stateStr,')'))

countyNames <- as.character(unique(simulations$countyNameState))
countyGroups <- split(countyNames, ceiling(seq_along(countyNames)/12))

i <- 1

for (countyGroup in countyGroups) {
  
  countyPlot <- simulations %>%
    filter(countyNameState %in% countyGroup,
           monthYear < make_date(2021,10,1)) %>%
    ggplot() +
      geom_vline(xintercept = make_date(2020,3,1)) +
      geom_line(mapping=aes(x=monthYear,y=deaths,color='Actual')) +
      geom_line(mapping=aes(x=monthYear,y=expDeaths,color='Simulated-RT')) +
      labs(x='Time',
           y='Deaths',
           colour='') +
      facet_wrap(~countyNameState, ncol = 4, nrow = 3) +
      theme(legend.position="bottom",
            axis.text.x = element_text(angle = 330))
  
  ggsave(here::here('figures',paste0('countyPlots',as.character(i),'.pdf')),
         device = 'pdf',width = 12,height = 7)
  
  i <- i + 1

}

```

```{r}

countiesIndex <- ''
i <- 1

for (countyGroup in countyGroups) {
  
  countiesIndex <- paste(countiesIndex,i,'\n')
  
  for (county in countyGroup) {
    
    countiesIndex <- paste(countiesIndex,county,'\n')
    
  }
  
  countiesIndex <- paste(countiesIndex,'\n')
  
  i <- i+1
  
}

cat(countiesIndex, file = here::here('figures','plotIndex.txt'))

```


