---
title: "Trend Graphs and Stacked Bars"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(tidyverse)
library(lubridate)
library(patchwork)
library(here)
library(scico)
library(grid)
library(tidytext)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/graphsPart2.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r, echo=F, message=F, warning=F}

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
countySets <- tibble(arrow::read_feather(here::here(outDir,'countySetsFinal.feather')))
states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r}

finalSimsFIPS <- read_csv(here::here(outDir,'exMortEstimatesMonthlyINLA.csv'))

```
```{r}

finalSimsFIPS <- finalSimsFIPS %>%
  rename(deaths = imputedDeaths) %>%
  mutate(year = year(monthYear)) 

```

```{r, echo=F, message=F, warning=F}

nationalTrend <- finalSimsFIPS %>% 
  drop_na(expDeathsMed,deaths) %>%
  group_by(monthYear) %>% 
  summarize(expDeaths = sum(expDeathsMed),
            deaths = sum(deaths)) %>%
  ggplot() +
    geom_line(mapping=aes(x=monthYear,y=deaths,color='Observed')) +
    geom_line(mapping=aes(x=monthYear,y=expDeaths,color='Predicted')) +
    labs(x='Time',
         y='Deaths',
         colour='') +
    theme_minimal() +
    theme(legend.position="bottom")

```

```{r}

pdf(here::here('figures','nationalTrend.pdf'), width = 8, height = 6)

nationalTrend

dev.off()

```

```{r, echo=FALSE, message=F, warning=F}

stateMeans <- finalSimsFIPS %>%
  drop_na() %>%
  filter(monthYear>=make_date(2019,1,1)) %>%
  group_by(state,BEARegion,monthYear) %>%
  summarize(excDeathRate = ((sum(deaths)-sum(expDeathsMed))/sum(pop))*100000) %>%
  ungroup()

trendPlots <- finalSimsFIPS %>%
  drop_na() %>%
  filter(monthYear>=make_date(2019,1,1)) %>%
  group_by(metroName,BEARegion,monthYear) %>%
  summarize(excDeathRate = ((sum(deaths)-sum(expDeathsMed))/sum(pop))*100000) %>%
  ungroup() %>%
  ggplot() +
  geom_line(data = stateMeans,
            mapping=aes(x=monthYear,y=excDeathRate,group=state),
            color='grey50', alpha=0.1) +
  geom_line(mapping=aes(x=monthYear,y=excDeathRate,group=metroName,color=metroName)) +
  scale_color_brewer(palette = "RdYlBu") +
  coord_cartesian(ylim=c(-25,160)) + 
  facet_wrap(~ BEARegion,ncol = 2) +
  labs(x='',
       y='Excess Death Rate (for 100,000 residents)',
       color='Metro Status') +
  theme_minimal() +
  theme(legend.position = 'bottom')

```

```{r}

pdf(here::here('figures','trendPlots.pdf'),width=10, height = 14)

trendPlots

dev.off()

```

```{r, echo=FALSE, message=F, warning=F}

BEABarsData2020 <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2020) %>%
  group_by(metroName,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),) %>%
  ungroup()

BEABarsData2021 <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2021) %>%
  group_by(metroName,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),) %>%
  ungroup()

```

```{r, echo=FALSE, message=F, warning=F}

stackBarsBEAPlot2020 <- BEABarsData2020 %>%
  ggplot() +
  geom_bar(mapping=aes(x=BEARegion,y=excDeaths,fill=metroName),
           position='stack',stat='identity') +
  scale_fill_brewer(palette = "RdYlBu") +
  coord_cartesian(ylim=c(0,175000)) +
  labs(x='',
       y='Excess Deaths',
       fill='Metro Status',
       title='2020') +
  theme_minimal() +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(angle=25,size=12))

stackBarsBEAPlot2021 <- BEABarsData2021 %>%
  ggplot() +
  geom_bar(mapping=aes(x=BEARegion,y=excDeaths,fill=metroName),
           position='stack',stat='identity') +
  scale_fill_brewer(palette = "RdYlBu") +
  coord_cartesian(ylim=c(0,175000)) +
  labs(x='',
       y='Excess Deaths',
       fill='Metro Status',
       title='2021') +
  theme_minimal() +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(angle=25,size=12))

```

```{r, echo=FALSE, message=F, warning=F, fig.height=16, fig.width=10}

statesBarsData2020 <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2020) %>%
  group_by(state,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeathsMed)) %>%
  arrange(desc(excDeaths), by_group=T) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  arrange(excDeaths,.by_group = T) %>%
  mutate(state = if_else(excDeaths<4200,'',state),
         BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),
         excDeathsCum = cumsum(excDeaths)) %>%
  arrange(desc(excDeaths),.by_group = T) %>%
  mutate(stateNum = row_number()) %>%
  ungroup()

statesBarsData2021 <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2021) %>%
  group_by(state,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeathsMed)) %>%
  arrange(desc(excDeaths), by_group=T) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  arrange(excDeaths,.by_group = T) %>%
  mutate(state = if_else(excDeaths<4200,'',state),
         BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),
         excDeathsCum = cumsum(excDeaths)) %>%
  arrange(desc(excDeaths),.by_group = T) %>%
  mutate(stateNum = row_number()) %>%
  ungroup()

```

```{r, echo=FALSE, message=F, warning=F, fig.height=16, fig.width=10}

stackBarsStatesPlot2020 <- statesBarsData2020 %>%
  ggplot(mapping=aes(x=BEARegion,y=excDeaths,group=stateNum,fill=excDeaths,label=state)) +
  geom_bar(position='stack',stat='identity') +
  geom_text(size = 4, position = position_stack(vjust=0.5)) + 
  coord_cartesian(ylim=c(0,175000)) +
  scale_fill_scico(palette='nuuk',limits=c(0,60000)) + 
  labs(x='',
       y='Excess Deaths',
       fill='Excess Deaths') +
  theme_minimal() +
  theme(legend.position = 'bottom',
        legend.key.width = unit(2,'cm'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size=12))

stackBarsStatesPlot2021 <- statesBarsData2021 %>%
  ggplot(mapping=aes(x=BEARegion,y=excDeaths,group=stateNum,fill=excDeaths,label=state)) +
  geom_bar(position='stack',stat='identity') +
  geom_text(size = 4, position = position_stack(vjust=0.5)) + 
  coord_cartesian(ylim=c(0,175000)) +
  scale_fill_scico(palette='nuuk',limits=c(0,60000)) + 
  labs(x='',
       y='Excess Deaths',
       fill='Excess Deaths') +
  theme_minimal() +
  theme(legend.position = 'bottom',
        legend.key.width = unit(2,'cm'),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size=12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

```

```{r, echo=F}

stackBarsPlot2020 <- ggplot() +
  geom_col(data = BEABarsData2020, 
           mapping=aes(x = BEARegionNum - 0.7, 
                       y = excDeaths,
                       fill= metroName), 
           width = .4) +
  scale_fill_brewer(palette = 'RdYlBu',name = 'Metro Status', 
                    guide = guide_legend(order = 1)) +
  scale_x_continuous(breaks = seq(1,8*2,2), 
                     labels = unique(BEABarsData2020$BEARegion)) +
  ggnewscale::new_scale_fill() +
  geom_col(data = statesBarsData2020, 
           mapping=aes(x = BEARegionNum + 0.2, 
                       y = excDeaths,
                       fill = excDeaths,
                       group = stateNum), 
           width = 1.5) +
  geom_text(data = statesBarsData2020, 
            mapping=aes(x = BEARegionNum + 0.2,
                        y = excDeathsCum - excDeaths/2,
                        label = state),
            size = 3) + 
  scale_fill_scico(palette='nuuk',limits=c(0,60000),
                   name = 'Excess Deaths', 
                   guide = guide_legend(order = 2)) +
  coord_cartesian(ylim=c(0,175000)) +
  labs(title='2020',
       x='',
       y='Excess Deaths') + 
  theme_minimal() +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        axis.title.y = element_text(size=14),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

```

```{r, echo=F}

stackBarsPlot2021 <- ggplot() +
  geom_col(data = BEABarsData2021, 
           mapping=aes(x = BEARegionNum - 0.7, 
                       y = excDeaths,
                       fill= metroName), 
           width = .4) +
    scale_fill_brewer(palette = 'RdYlBu',name = 'Metro Status', 
                      guide = guide_legend(order = 1)) +
  scale_x_continuous(breaks = seq(1,8*2,2), 
                     labels = unique(BEABarsData2021$BEARegion)) +
  ggnewscale::new_scale_fill() +
  geom_col(data = statesBarsData2021, 
           mapping=aes(x = BEARegionNum + 0.2, 
                       y = excDeaths,
                       fill = excDeaths,
                       group = stateNum), 
           width = 1.5) +
  geom_text(data = statesBarsData2021, 
            mapping=aes(x = BEARegionNum + 0.2,
                        y = excDeathsCum - excDeaths/2,
                        label = state),
            size = 3) + 
  scale_fill_scico(palette='nuuk',limits=c(0,60000),
                   name = 'Excess Deaths', 
                   guide = guide_legend(order = 2)) +
  coord_cartesian(ylim=c(0,175000)) +
  labs(title='2021',
       x='',
       y='Excess Deaths') + 
  theme_minimal() +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        axis.title.y = element_text(size=14),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

```

```{r}

pdf(here::here('figures','stackBarsPlot.pdf'), width=14, height = 14)

(stackBarsBEAPlot2020 + stackBarsStatesPlot2020 +
stackBarsBEAPlot2021 + stackBarsStatesPlot2021) +
plot_layout(widths=c(1,3), guides='collect') & theme(legend.position = 'bottom')

dev.off()

```

```{r}

pdf(here::here('figures','stackBarsPlotAlt.pdf'), width=12, height = 14)

stackBarsPlot2020 / stackBarsPlot2021 + plot_layout(guides='collect') & theme(legend.position = 'bottom',legend.box="vertical", legend.margin=margin())

dev.off()

```

```{r, echo=FALSE, message=F, warning=F}

BEABarsData2020PC <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2020) %>%
  group_by(metroName,BEARegion,FIPSCode,year) %>%
  summarize(pop = mean(pop),
            excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(metroName,BEARegion,year) %>%
  mutate(excDeaths = sum(excDeaths),
         pop = sum(pop),
         excDeathsPC = (excDeaths/pop)*100000) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),) %>%
  ungroup()

BEABarsData2021PC <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2021) %>%
  group_by(metroName,BEARegion,FIPSCode,year) %>%
  summarize(pop = mean(pop),
            excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(metroName,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeaths),
            pop = sum(pop),
            excDeathsPC = (excDeaths/pop)*100000) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),) %>%
  ungroup()

```

```{r, echo=FALSE, message=F, warning=F, fig.height=16, fig.width=10}

statesBarsData2020PC <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2020) %>%
  group_by(BEARegion,state,FIPSCode,year) %>%
  summarize(pop = mean(pop),
            excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(state,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeaths),
            pop = sum(pop),
            excDeathsPC = (excDeaths/pop)*100000) %>%
  arrange(desc(excDeathsPC), by_group=T) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  arrange(excDeathsPC,.by_group = T) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),
         excDeathsCumPC = cumsum(excDeathsPC)) %>%
  arrange(desc(excDeathsPC),.by_group = T) %>%
  mutate(stateNum = row_number()) %>%
  ungroup()

statesBarsData2021PC <- finalSimsFIPS %>%
  drop_na() %>%
  filter(year==2021) %>%
  group_by(BEARegion,state,FIPSCode,year) %>%
  summarize(pop = mean(pop),
            excDeaths = sum(excDeathsMed)) %>%
  ungroup() %>%
  group_by(state,BEARegion,year) %>%
  summarize(excDeaths = sum(excDeaths),
            pop = sum(pop),
            excDeathsPC = (excDeaths/pop)*100000) %>%
  arrange(desc(excDeathsPC), by_group=T) %>%
  ungroup() %>%
  group_by(BEARegion) %>%
  arrange(excDeathsPC,.by_group = T) %>%
  mutate(BEARegionNum = cur_group_id(),
         BEARegionNum = BEARegionNum + (BEARegionNum-1),
         excDeathsCumPC = cumsum(excDeathsPC)) %>%
  arrange(desc(excDeathsPC),.by_group = T) %>%
  mutate(stateNum = row_number()) %>%
  ungroup()

```

```{r, echo=F}

BEAHBarsPlot2020 <- ggplot() +
  geom_col(data = BEABarsData2020PC, 
           mapping=aes(x = BEARegion, 
                       y = excDeathsPC,
                       fill= metroName), 
           position = position_dodge()) +
  scale_fill_brewer(palette = 'RdYlBu',name = 'Metro Status') +
  labs(title='2020',
       x='',
       y='Excess Deaths per 100,000 Residents') + 
  theme_minimal() +
  coord_flip(ylim=c(0,310)) + 
  theme(legend.position = 'bottom',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

BEAHBarsPlot2021 <- ggplot() +
  geom_col(data = BEABarsData2021PC, 
           mapping=aes(x = BEARegion, 
                       y = excDeathsPC,
                       fill= metroName), 
           position = position_dodge()) +
  scale_fill_brewer(palette = 'RdYlBu',name = 'Metro Status') +
  labs(title='2021',
       x='',
       y='Excess Deaths per 100,000 Residents') + 
  coord_flip(ylim=c(0,310)) + 
  theme_minimal() +
  theme(legend.position = 'bottom',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```

```{r, echo=F}

stateHBarsPlot2020 <- ggplot(data = statesBarsData2020PC) +
  geom_col(mapping=aes(x = reorder_within(x=state, by=-excDeathsPC,within=BEARegion), 
                       y = excDeathsPC,
                       fill = excDeathsPC), 
           position = position_dodge()) +
  scale_fill_scico(palette='nuuk',limits=c(0,310),
                   name = 'Excess Deaths per 100,000 Residents') +
  scale_x_reordered() +
  coord_flip(ylim=c(0,310)) + 
  labs(title='2020',
       x='',
       y='Excess Deaths per 100,000 Residents') + 
  facet_grid(BEARegion~.,scales = "free_y", space = "free_y") +
  theme_minimal() +
  theme(legend.position = 'bottom',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

stateHBarsPlot2021 <- ggplot(data = statesBarsData2021PC) +
  geom_col(mapping=aes(x = reorder_within(x=state, by=-excDeathsPC,within=BEARegion), 
                       y = excDeathsPC,
                       fill = excDeathsPC), 
           position = position_dodge()) +
  scale_fill_scico(palette='nuuk',limits=c(0,310),
                   name = 'Excess Deaths per 100,000 Residents') +
  scale_x_reordered() +
  coord_flip(ylim=c(0,310)) + 
  labs(title='2021',
       x='',
       y='Excess Deaths per 100,000 Residents') + 
  facet_grid(BEARegion~.,scales = "free_y", space = "free_y") +
  theme_minimal() +
  theme(legend.position = 'bottom',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

```

```{r}

pdf(here::here('figures','HBarsPlotPC.pdf'), width=12, height = 16)

(stateHBarsPlot2020 + stateHBarsPlot2021 +
 BEAHBarsPlot2020 + BEAHBarsPlot2021) + 
plot_layout(guides='collect',heights = c(5,2)) & 
theme(legend.position = 'bottom',legend.box="vertical", legend.margin=margin())

dev.off()

```

```{r, echo=FALSE, message=F, warning=F}

largestCounties <- finalSimsFIPS %>%
  drop_na() %>%
  group_by(BEARegion,FIPSCode,metroName) %>%
  summarize(popMean = mean(pop)) %>%
  ungroup() %>%
  group_by(BEARegion,metroName) %>%
  slice(which.max(popMean)) %>%
  pull(FIPSCode)

largestCountiesData <- finalSimsFIPS %>%
  filter(FIPSCode %in% largestCounties) %>%
  mutate(imputed = if_else(deaths<10,T,F),
         deathRate = (deaths/pop)*100000,
         deathRateLead = lead(deathRate),
         expDeathRateLow = (expDeathsLow/pop)*100000,
         expDeathRateMed = (expDeathsMed/pop)*100000,
         expDeathRateUp = (expDeathsUp/pop)*100000) %>%
  group_by(FIPSCode) %>%
  mutate(deathRateLead = lead(deathRate)) %>%
  ungroup()

largestCountiesPlots <- largestCountiesData %>%
  ggplot() +
  geom_segment(mapping=aes(x=monthYear,xend=lead(monthYear),
                           y=deathRate,yend=deathRateLead,
                           color='Observed',linetype=imputed)) +
  geom_line(mapping=aes(x=monthYear,y=expDeathRateMed,color='Expected')) +
  geom_ribbon(mapping=aes(x=monthYear,ymin=expDeathRateLow,ymax=expDeathRateUp,
                          fill='90% Posterior Interval'),alpha=0.2) +
  geom_label(mapping=aes(x=make_date(2018,6,1),y=175,
                         label=paste0(countyName,' (',stateStr,')')),size=3) +
  geom_hline(yintercept = 10, linetype='dotted') +
  scale_color_manual(name='',
                     breaks=c('Observed', 
                              'Expected'),
                     values=c('Observed'='red', 
                              'Expected'='black')) + 
  scale_fill_manual(name='',
                    breaks=c('90% Posterior Interval'),
                    values=c('90% Posterior Interval'='black')) + 
  coord_cartesian(ylim=c(20,200)) +
  facet_grid(rows = vars(BEARegion), cols=vars(metroName)) +
  labs(x='',
       y='Observed and Expected Number of Deaths (for 100,000 residents)',
       color='',
       fill='',
       linetype='Imputed') +
  theme_minimal() +
  theme(legend.position = 'bottom')

```

```{r}

pdf(here::here('figures','largestCountiesPlots.pdf'),width=12, height = 14)

largestCountiesPlots

dev.off()

```

```{r, echo=F, message=F, warning=F}

# Creating a plot with predicted vs actual rates for each county in groups of
# 12 (ordered by FIPS code.

finalSimsFIPS <- finalSimsFIPS %>%
  mutate(countyNameState = paste0(countyName,' (',state,')'))

countyNames <- as.character(unique(finalSimsFIPS$countyNameState))
countyGroups <- split(countyNames, ceiling(seq_along(countyNames)/12))

i <- 1

for (countyGroup in countyGroups) {
  
  countyPlot <- finalSimsFIPS %>%
    filter(countyNameState %in% countyGroup) %>%
    mutate(imputed = if_else(deaths<10,T,F),
           deathRate=(deaths/pop)*100000,
           expDeathsLow=(expDeathsLow/pop)*100000,
           expDeathsMed=(expDeathsMed/pop)*100000,
           expDeathsUp=(expDeathsUp/pop)*100000) %>%
  group_by(FIPSCode) %>%
  mutate(deathRateLead = lead(deathRate)) %>%
  ungroup() %>%
    ggplot() +
      geom_vline(xintercept = make_date(2020,3,1)) +
      geom_line(mapping=aes(x=monthYear,y=expDeathsMed,color='Predicted')) +
      geom_ribbon(mapping=aes(x=monthYear,ymin=expDeathsLow,ymax=expDeathsUp,
                              fill='80% Posterior Intervals'),alpha=0.2) +
      geom_segment(mapping=aes(x=monthYear,xend=lead(monthYear),
                               y=deathRate,yend=deathRateLead,
                               color='Observed',linetype=imputed)) +
      scale_color_manual(name='',
                         breaks=c('Observed', 'Predicted'),
                         values=c('Observed'='red', 'Predicted'='black')) + 
      scale_fill_manual(name='',
                        breaks=c('90% Posterior Intervals'),
                        values=c('90% Posterior Intervals'='black')) + 
      labs(x='',
           y='Observed and Expected Number of Deaths (for 100,000 residents)',
           colour='',
           fill='',
           linetype='Imputed') +
      facet_wrap(~countyNameState, ncol = 4, nrow = 3) +
      theme_minimal() +
      theme(legend.position="bottom",
            axis.text.x = element_text(angle = 330))
  
  ggsave(here::here('figures','countyPlots',paste0('countyPlots',as.character(i),'.pdf')),
         device = 'pdf',width = 12,height = 7)
  
  i <- i + 1

}

```

```{r, echo=F}

# Creating the plot directories to make it easier to find which file contains a
# given county

countiesIndex <- ''
i <- 1

for (countyGroup in countyGroups) {
  
  countiesIndex <- paste(countiesIndex,i,'\n')
  
  for (county in countyGroup) {
    
    countiesIndex <- paste(countiesIndex,county,'\n')
    
  }
  
  countiesIndex <- paste(countiesIndex,'\n')
  
  i <- i+1
  
}

cat(countiesIndex, file = here::here('figures','countyPlots','plotIndex.txt'))

```

