---
title: "County-Level Mortality Model (Yearly) - Estimation"
author: "Eugenio Paglino"
date: "\today"
output:
  html_document:
    df_print: paged
---

```{r, message=F,warning=F}

# Loading necessary packages

library(INLA)
library(here)
library(sf)
library(spdep)
library(USAboundaries)
library(tidyverse)

```

```{r, echo=FALSE, message=F, warning=F}

rm(list=ls())

here::i_am('R/modelsFitYearly.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

set.seed(42)

```

```{r}

ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))

allFIPS <- ACYearlyData %>% pull(FIPSCode) %>% unique()
allStates <- ACYearlyData %>% pull(stateFIPS) %>% unique()

ACYearlyData <- ACYearlyData %>%
  filter(stateFIPS %in% sample(stateFIPS,10,replace=T))

```


```{r}

counties <- us_counties()
# Transform to Albers for making map of US
counties <- st_transform(counties, 5070)

counties <- counties %>%
  select(geoid,geometry) %>%
  rename(FIPSCode = geoid) %>%
  mutate(FIPSCode = case_when(FIPSCode == '02013' ~ '02010',
                              FIPSCode == '02188' ~ '02140',
                              FIPSCode == '02230' ~ '02232',
                              FIPSCode == '02063' ~ '02261',
                              TRUE ~ FIPSCode)) %>%
  filter(FIPSCode %in% unique(ACYearlyData %>% pull(FIPSCode))) %>%
  arrange(FIPSCode)

```

```{r}

neighbors <- poly2nb(counties)

# We can edit neighbors manually but we need to be very careful because
# neighborhood is here a symmetric relationship so that everything breaks
# (in INLA) if A is B's neighbor. but B is not A's neighbor.

#neighbors[[68]] <- as.integer(c(70))
#neighbors[[71]] <- as.integer(c(70))
#neighbors[[70]] <- sort(as.integer(c(neighbors[[70]], 68, 71)))

nb2INLA(here::here(outDir,'neighborsExY.graph'),neighbors)
inla.graph <- inla.read.graph(here::here(outDir,'neighborsExY.graph'))
adj.matrix <- inla.graph2matrix(inla.graph)

```

```{r, echo=F}

ACYearlyData <- ACYearlyData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id(),
         FIPSCode2 = FIPSCode) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(yearID = cur_group_id(),
         yearID2 = yearID,
         yearID3 = yearID) %>%
  ungroup() %>%
  mutate(CDRCensored = if_else(year>2019,NA_real_,CDR),
         deathsCensored = if_else(year>2019,NA_integer_,deaths)) %>%
  arrange(FIPSCode,year)

```

```{r}

suppressionData <- ACYearlyData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  summarize(nonMissingVals = sum(!is.na(deaths)))

```

```{r}
# Function to compute the Root Mean Squared Error (RMSE) between two series
RMSE <- function(series1,series2) {
  
  return(sqrt(mean((series1 - series2)^2,na.rm=T)))
  
}
```

```{r}

# INLA SET UP
# priors
hyper.bym <- list(prec.unstruct=list(param=c(1,0.1)),
                  prec.spatial=list(param=c(1,0.1)))
hyper.iid <- list(theta = list(prior="pc.prec", param=c(1, 0.01)))

formula <- deathsCensored ~ 1 + offset(log(pop)) + 
                                f(FIPSCode, model='bym', hyper=hyper.bym, 
                                  graph=inla.graph, scale.model=T) +
                                f(yearID,model='iid',hyper=hyper.iid,
                                  constr=T) +
                                f(yearID2,model='rw2',hyper=hyper.iid,
                                  scale.model=T) +
                                f(FIPSCode2,model='besag',graph=inla.graph,
                                  group = yearID3,scale.model = T,
                                  control.group = list(model='rw2'))
                                
# Under Poisson uses default set up
control.family=inla.set.control.family.default()

```

```{r}

# We re-estimated the last model with INLA so that we can use it to 
# build posterior intervals for the predictions.

model.Y.BYM.LinearTime.INLA <- ACYearlyData %>%
 mutate(deathsCensored = if_else(year>=2019,NA_integer_,deathsCensored)) %>%
 inla(formula,
       data = .,
       family = "poisson",
       num.threads = round(parallel::detectCores()*0.7),
       control.family=control.family,
       control.compute=list(config = TRUE))

# Note: INLA is a bit tricky, error messages are not very informative.

```

```{r}

n.sim <- 1000
draws <- inla.posterior.sample(n.sim, model.Y.BYM.LinearTime.INLA)
model.names <- row.names(draws[[1]]$latent)
y.names <- grep("Predictor", model.names)

death.draws.raw <- sapply(draws, function(x) exp(x$latent[y.names]))
death.draws <- t(apply(death.draws.raw,M=1,function(x) rpois(n.sim,x)))
mean.deaths <- apply(death.draws,M=1,function(x) mean(x))
up.deaths <- apply(death.draws,M=1,function(x) quantile(x,0.95))
low.deaths <- apply(death.draws,M=1,function(x) quantile(x,0.05))

```

```{r}

testData <- tibble(deaths = pull(ACYearlyData,deaths),
                   CDR = pull(ACYearlyData,CDR),
                   pop = pull(ACYearlyData,pop),
                   FIPSCode = pull(ACYearlyData,FIPSCode),
                   year = pull(ACYearlyData,year))

testData <- testData %>% 
  mutate(expDeathsMean = mean.deaths,
         expDeathsUp = up.deaths,
         expDeathsLow = low.deaths,
         expRateMean = (expDeathsMean/pop)*100000,
         expRateUp = (expDeathsUp/pop)*100000,
         expRateLow = (expDeathsLow/pop)*100000)

testData <- testData %>%
  left_join(suppressionData,by='FIPSCode') %>%
  mutate(expDeathsMean = if_else(nonMissingVals < 5,5,expDeathsMean),
         expDeathsUp = if_else(nonMissingVals < 5,10,expDeathsUp),
         expDeathsLow = if_else(nonMissingVals < 5,0,expDeathsLow),
         expRateMean = (expDeathsMean/pop)*100000,
         expRateUp = (expDeathsUp/pop)*100000,
         expRateLow = (expDeathsLow/pop)*100000)

```

```{r}

RMSE(testData %>% filter(year<2019) %>% pull(expDeathsMean),
     testData %>% filter(year<2019) %>% pull(deaths))

RMSE(testData %>% filter(year==2019) %>% pull(expDeathsMean),
     testData %>% filter(year==2019) %>% pull(deaths))

RMSE(testData %>% filter(year<2020) %>% pull(expDeathsMean),
     testData %>% filter(year<2020) %>% pull(deaths))

```

```{r}

# To examine: c(663,628,334,54,85,479)

numFIPS <- length(unique(pull(ACYearlyData,FIPSCode)))

testFigure <- testData %>%
  filter(FIPSCode %in% sample(1:numFIPS,6)) %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=CDR,color='Observed')) +
  geom_line(mapping=aes(x=year,y=expRateMean,color='Expected')) +
  geom_ribbon(mapping=aes(x=year,ymin=expRateLow,ymax=expRateUp,
                          fill='Expected'),alpha=0.3) +
  labs(x='Deaths',
       y='',
       color='',
       fill='') +
  facet_wrap(~FIPSCode) +
  guides(fill='none')

testFigure

```
```{r}

testFigure <- testData %>%
  group_by(year) %>%
  summarise(across(everything(), ~ sum(.x,na.rm=T))) %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=deaths,color='Observed')) +
  geom_line(mapping=aes(x=year,y=expDeathsMean,color='Expected')) +
  geom_ribbon(mapping=aes(x=year,ymin=expDeathsLow,ymax=expDeathsUp,
                          fill='Expected'),alpha=0.3) +
  labs(x='Deaths',
       y='',
       color='',
       fill='') +
  facet_wrap(~FIPSCode) +
  guides(fill='none')

testFigure

```


