---
title: "County-Level Mortality Model (Yearly) - Estimation"
author: "Eugenio Paglino"
date: "\today"
output:
  html_document:
    df_print: paged
---

```{r, message=F,warning=F}

# Loading necessary packages

library(INLA)
library(here)
library(tidyverse)

```

```{r, echo=FALSE, message=F, warning=F}

rm(list=ls())

here::i_am('R/modelsFitYearly.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r}

ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))

```

```{r}

inla.graph <- inla.read.graph(here::here(outDir,'neighbors.graph'))
adj.matrix <- inla.graph2matrix(inla.graph)

```

```{r, echo=F}

ACYearlyData <- ACYearlyData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id(),
         FIPSCode2 = FIPSCode) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(yearID = cur_group_id(),
         yearID2 = yearID,
         yearID3 = yearID) %>%
  ungroup() %>%
  mutate(CDR = if_else(year>2019,NA_real_,CDR),
         deathsCensored = if_else(year>2019,NA_integer_,deaths)) %>%
  arrange(FIPSCode,year)

```

```{r}

# INLA SET UP
# priors
hyper.bym <- list(theta1 = list('PCprior', c(1, 0.01)), theta2 = list('PCprior', c(0.5, 0.5)))
hyper.iid <- list(theta = list(prior="pc.prec", param=c(1, 0.01)))

formula <- deathsCensored ~ 1 + offset(log(pop)) + 
                                f(FIPSCode, model='bym2', hyper=hyper.bym, 
                                  graph=inla.graph, scale.model=T) +
                                f(yearID,model='iid',hyper=hyper.iid,
                                  constr=T) +
                                f(yearID2,model='rw1',hyper=hyper.iid,
                                  scale.model=T)
                                
# Under Poisson uses default set up
control.family=inla.set.control.family.default()

```

```{r}

# We re-estimated the last model with INLA so that we can use it to 
# build posterior intervals for the predictions.

model.Y.BYM.Dynamic.INLA <- ACYearlyData %>%
  inla(formula,
       data = .,
       family = "poisson",
       num.threads = round(parallel::detectCores()*0.7),
       control.family=control.family,
       control.compute=list(config = TRUE))

# Note: INLA is a bit tricky, error messages are not very informative.

```
```{r}

n.sim <- 1000
draws <- inla.posterior.sample(n.sim, model.Y.BYM.Dynamic.INLA)
model.names <- row.names(draws[[1]]$latent)
y.names <- grep("Predictor", model.names)

rate.draws <- sapply(draws, function(x) exp(x$latent[y.names]))
death.draws.y <- apply(rate.draws,M=1,function(x) rpois(n.sim,x))
mean.deaths <- apply(death.draws.y,M=2,function(x) mean(x))
up.deaths <- apply(death.draws.y,M=2,function(x) quantile(x,0.95))
low.deaths <- apply(death.draws.y,M=2,function(x) quantile(x,0.05))

```

```{r}

suppressionData <- ACYearlyData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  summarize(nonMissingVals = sum(!is.na(deaths)))

```

```{r}

testData <- tibble(deaths = pull(ACYearlyData,deaths),
                   CDR = pull(ACYearlyData,CDR),
                   pop = pull(ACYearlyData,pop),
                   FIPSCode = pull(ACYearlyData,FIPSCode),
                   year = pull(ACYearlyData,year))

testData <- testData %>% 
  mutate(expDeathsMean = mean.deaths,
         expDeathsUp = up.deaths,
         expDeathsLow = low.deaths,
         expRateMean = (expDeathsMean/pop)*100000,
         expRateUp = (expDeathsUp/pop)*100000,
         expRateLow = (expDeathsLow/pop)*100000)

testData <- testData %>%
  left_join(suppressionData,by='FIPSCode') %>%
  mutate(expDeathsMean = if_else(nonMissingVals < 5,5,expDeathsMean),
         expDeathsUp = if_else(nonMissingVals < 5,10,expDeathsUp),
         expDeathsLow = if_else(nonMissingVals < 5,0,expDeathsLow),
         expRateMean = (expDeathsMean/pop)*100000,
         expRateUp = (expDeathsUp/pop)*100000,
         expRateLow = (expDeathsLow/pop)*100000)

```

```{r}

# To examine: c(663,628,334,54,85,479)

numFIPS <- length(unique(pull(ACYearlyData,FIPSCode)))

testFigure <- testData %>%
  filter(FIPSCode %in% sample(1:numFIPS,6)) %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=deaths/pop,color='Observed')) +
  geom_line(mapping=aes(x=year,y=expDeathsMean/pop,color='Expected')) +
  geom_ribbon(mapping=aes(x=year,ymin=expDeathsLow/pop,ymax=expDeathsUp/pop,
                          fill='Expected'),alpha=0.3) +
  labs(x='Deaths',
       y='',
       color='',
       fill='') +
  facet_wrap(~FIPSCode) +
  guides(fill='none')

testFigure

```

```{r}
# We save the posterior samples so we can retrieve them whenever we need

save(death.draws.y,file=here::here('R','RObjects','simYearlySimple.RData'))

```

```{r, eval=F}

# We save our models so that we can easily load them where and when we
# need them without having to fit them again.

save(model.Y.BYM.Dynamic.INLA, file = here::here('R','RObjects','modelYBYMDynamicINLA.RData'))

```

