---
title: "Ridge Graph"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(lubridate)
library(here)
library(ggridges)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/ridgesGraph.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r, echo=F, message=F, warning=F}

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))
COVIDYearlyData <- tibble(arrow::read_feather(here::here(outDir,'COVIDYearlyData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))

```

```{r}

load(here('R','RObjects','simMonthly.RData'))
load(here('R','RObjects','simYearly.RData'))

```

```{r, echo=F}

# Computing overall distribution of deaths by month

monthWeights <- ACData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  select(month,monthWeight)

monthWeights <- monthWeights %>% pull(monthWeight)

```

```{r}

n.sim <- 1000
years <- 2015:2022
FIPSCodes <- as.numeric(unique(ACData$FIPSCode))

death.draws.y.partial <- t(death.draws.y[,pull(ACYearlyData,year)>=2015])
death.draws.y.aug <- death.draws.y.partial[rep(1:nrow(death.draws.y.partial), each = 12), ]

monthWeights.matrix <- as.matrix(rep(monthWeights,length(years)*length(FIPSCodes)))
monthWeights.matrix <- monthWeights.matrix[, rep(1,n.sim)]

death.draws.y.aug <- death.draws.y.aug*monthWeights.matrix
death.draws.y.aug <- death.draws.y.aug[as.vector(sapply(1:3127,function(x) (1:86)+(96*(x-1)))),]

```

```{r}

death.draws <- as.list(as.data.frame(death.draws))
death.draws.y.aug <- as.list(as.data.frame(t(death.draws.y.aug)))

rm(list=c('death.draws.y','death.draws.y.partial','monthWeights.matrix'))

```

```{r, echo=F}

suppressionData <- read_csv(here::here(outDir,'suppressionData.csv'))
  
```

```{r, echo=F}

# We set which estimate to used based on the relative average error of the

diffTreshold <- 0.05

ACData <- ACData %>%
  left_join(suppressionData,by='FIPSCode') %>%
  mutate(deathsDiffPct = if_else(is.na(deathsDiffPct),0,deathsDiffPct))

death.draws <- if_else(pull(ACData,deathsDiffPct) > diffTreshold,
                       death.draws.y.aug,
                       death.draws)

rm(list=c('death.draws.y.aug'))

```

```{r}

simulationsDF <- as_tibble(matrix(unlist(death.draws), ncol = n.sim, byrow = TRUE))

simulationsDF <- simulationsDF %>% 
  mutate(FIPSCode = ACData %>% pull(FIPSCode),
         year = ACData %>% pull(year),
         month = ACData %>% pull(month),
         monthYear = make_date(year=year,month=month,day=1)) %>%
  relocate(FIPSCode,year,month,monthYear)

```

```{r}

plotDataStates <- simulationsDF %>%
  left_join(ACData,by=c('FIPSCode','month','year')) %>%
  filter(!(state %in% c('Wyoming','Maine') & year(monthYear) > 2021)) %>%
  group_by(state,census_division,monthYear) %>%
  summarize(across(V1:V1000, ~ sum(.x)),
            imputedDeaths = sum(imputedDeaths)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(state,census_division,monthYear) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95))) %>%
  ungroup() %>%
  mutate(deaths = expDeathsUp + excDeathsMed)

divisionTotals <- simulationsDF %>%
  left_join(ACData,by=c('FIPSCode','month','year')) %>%
  filter(!(state %in% c('Wyoming','Maine') & year(monthYear) > 2021)) %>%
  group_by(census_division,monthYear) %>%
  summarize(across(V1:V1000, ~ sum(.x)),
            imputedDeaths = sum(imputedDeaths)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(census_division,monthYear) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95))) %>%
  ungroup() %>%
  mutate(deaths = expDeathsUp + excDeathsMed,
         state=paste('Total -',census_division))

nationTotals <- simulationsDF %>%
  left_join(ACData,by=c('FIPSCode','month','year')) %>%
  filter(!(state %in% c('Wyoming','Maine') & year(monthYear) > 2021)) %>%
  group_by(monthYear) %>%
  summarize(across(V1:V1000, ~ sum(.x)),
            imputedDeaths = sum(imputedDeaths)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(monthYear) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95))) %>%
  ungroup() %>%
  mutate(deaths = expDeathsUp + excDeathsMed,
         state='Nation Total',
         census_division = 'Nation Total')

```

```{r}

plotData <- plotDataStates %>%
  add_row(divisionTotals) %>%
  add_row(nationTotals)

```

```{r, echo=F, message=F, warning=F}

relativeExcBreaks <- c(-5,0.2,0.4,0.6,0.80,1,1.5,2,5)

plotData <- plotData %>%
  filter(monthYear >= make_date(2020,1,1)) %>%
  mutate(relativeExc = (deaths/expDeathsMed)-1,
         relativeExcDiscrete = factor(cut(relativeExc,relativeExcBreaks),
                                      labels=c('<=20%','(20%,40%]','(40%,60%]',
                                               '(60%,80%]','(80%,100%]','(100%,150%]',
                                               '(150%,200%]','>200%')),
         significant = if_else(excDeathsLow > 0,'>= 95%','<95%'),
         time = as.numeric(monthYear) - min(as.numeric(monthYear)))

sortedDivisions <- plotData %>%
  filter(census_division != 'Nation Total') %>%
  arrange(census_division) %>%
  pull(census_division) %>%
  unique()

sortedDivisions <- c(sortedDivisions,'Nation Total')

sortedStates <- plotData %>% 
  filter(!(str_detect(state,'Total'))) %>%
  group_by(state) %>%
  summarize(relativeExc = max(relativeExc,na.rm=T)) %>% 
  ungroup() %>%
  arrange(relativeExc) %>%
  pull(state)

sortedStates <- c(sortedStates,paste('Total -',sortedDivisions[-10]),'Nation Total')
statesNum <- length(sortedStates)
sortedLetters <- sort(c(letters,LETTERS,paste0(letters,LETTERS)),decreasing = T)[1:statesNum]

plotData <- plotData %>%
  mutate(state = factor(state,
                        levels=sortedStates,
                        labels=sortedLetters),
         census_division = factor(census_division,
                                  levels = sortedDivisions))

```

```{r}

stateIDs <- plotData %>%
  group_by(census_division,state) %>%
  summarize(groupCode = cur_group_id()) %>%
  ungroup() %>%
  group_by(census_division) %>%
  mutate(stateCode = 1:n()) %>%
  ungroup()
  
plotData <- plotData %>%
  left_join(stateIDs,by=c('state','census_division'))

```
```{r, fig.height=10, fig.width=6}

plotData <- plotData %>%
  group_by(state) %>%
  mutate(relativeExcLead = lead(relativeExc))

```

```{r, fig.height=10, fig.width=6}

allDates <- unique(pull(plotData,monthYear))

ridgesGraph <- plotData %>%
  ggplot() +
  #geom_tile(mapping=aes(x=monthYear,y=state,width=31,fill=deaths/expDeathsMed)) +
  geom_ridgeline_gradient(mapping=aes(x=monthYear,
                                      height=relativeExc,
                                      y=state,
                                      fill=as.numeric(relativeExcDiscrete)),
                               color=NA,
                               stat='identity',
                               scale=1.5) +
  geom_segment(mapping=aes(x=monthYear,
                           xend = lead(monthYear),
                           y = stateCode + relativeExc*1.5,
                           yend = stateCode + relativeExcLead*1.5,
                           linetype=significant)) +
  geom_vline(xintercept=make_date(2020,3,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2020,9,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2020,10,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,2,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,8,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,10,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,11,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2022,2,1),linetype='dotted') +  
  annotate('text',x=make_date(2020,6,1),y=1,label='Initial Wave',size=3) +
  annotate('text',x=make_date(2020,12,1),y=1,label='Winter Peak',size=3) +
  annotate('text',x=make_date(2021,9,1),y=1,label='Delta',size=3) +
  annotate('text',x=make_date(2021,12,15),y=1,label='Omicron',size=3) +
  scale_x_date(breaks=allDates,date_labels="%b-%y") +
  scale_y_discrete(breaks=sortedLetters,labels=sortedStates) +
  scale_fill_distiller(palette='Oranges',direction = 1,na.value = 'grey90',
                       breaks=1:8,
                       labels=c('<=20%','(20%,40%]','(40%,60%]',
                                '(60%,80%]','(80%,100%]','(100%,150%]',
                                '(150%,200%]','>200%')) +
  scale_linetype_manual(values=c('dotted','solid')) +
  labs(y='',
       x = '',
       fill='Relative\nExcess (%)',
       linetype='Probability of\nRelative Excess > 0') +
  facet_grid(census_division~.,scales = "free_y", space = "free_y") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        legend.position = 'bottom',
        legend.key.width = unit(2,'cm'),
        legend.title = element_text(hjust=0.5),
        strip.text.y = element_text(angle = 0),
        axis.text.x = element_text(angle=30)) +
  guides(linetype=guide_legend(nrow = 2),
         fill=guide_legend(title.hjust = 0)) # No idea why this made the legend discrete

ridgesGraph

```

```{r}

pdf(here::here('figures','ridgesGraph.pdf'), width = 12, height = 16)

ridgesGraph

dev.off()

```
