---
title: "Ridge Graph"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(lubridate)
library(here)
library(ggridges)
library(ggh4x)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/ridgesGraphAlt.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r}
load(here('R','RObjects','simulationsDF.RData'))
```

```{r}

plotDataStates <- simulationsDF %>%
  group_by(state,census_division,metroCat2,monthYear) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            imputedDeaths = sum(imputedDeaths,na.rm=T)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(state,census_division,metroCat2,monthYear) %>%
  summarize(deaths=mean(imputedDeaths),
            expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            relExcLow = quantile(excDeaths/expDeaths,probs=c(0.05)),
            relExcMed = quantile(excDeaths/expDeaths,probs=c(0.5)),
            relExcUp = quantile(excDeaths/expDeaths,probs=c(0.95))) %>%
  ungroup()

divisionTotals <- simulationsDF %>%
  group_by(census_division,metroCat2,monthYear) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            imputedDeaths = sum(imputedDeaths,na.rm=T)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(census_division,metroCat2,monthYear) %>%
  summarize(deaths=mean(imputedDeaths),
            expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            relExcLow = quantile(excDeaths/expDeaths,probs=c(0.05)),
            relExcMed = quantile(excDeaths/expDeaths,probs=c(0.5)),
            relExcUp = quantile(excDeaths/expDeaths,probs=c(0.95))) %>%
  ungroup() %>%
  mutate(state=paste('Total -',census_division))

nationTotals <- simulationsDF %>%
  group_by(monthYear,metroCat2) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            imputedDeaths = sum(imputedDeaths,na.rm=T)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths) %>%
  group_by(monthYear,metroCat2) %>%
  summarize(deaths=mean(imputedDeaths),
            expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            relExcLow = quantile(excDeaths/expDeaths,probs=c(0.05)),
            relExcMed = quantile(excDeaths/expDeaths,probs=c(0.5)),
            relExcUp = quantile(excDeaths/expDeaths,probs=c(0.95))) %>%
  ungroup() %>%
  mutate(state='Nation Total',
         census_division = 'Nation Total')

```

```{r}

plotData <- plotDataStates %>%
  add_row(divisionTotals) %>%
  add_row(nationTotals)

```

```{r, echo=F, message=F, warning=F}

relativeExcBreaks <- c(-5,0.2,0.4,0.6,0.80,1,1.5,2,5)

plotData <- plotData %>%
  filter(monthYear >= make_date(2020,1,1)) %>%
  mutate(relativeExcDiscrete = factor(cut(relExcMed,relativeExcBreaks),
                                      labels=c('<=20%','(20%,40%]','(40%,60%]',
                                               '(60%,80%]','(80%,100%]','(100%,150%]',
                                               '(150%,200%]','>200%')),
         significant = if_else(excDeathsLow > 0,'>= 90%','<90%'),
         time = as.numeric(monthYear) - min(as.numeric(monthYear)))

sortedDivisions <- plotData %>%
  filter(census_division != 'Nation Total') %>%
  arrange(census_division) %>%
  pull(census_division) %>%
  unique()

sortedDivisions <- c(sortedDivisions,'Nation Total')

sortedStates <- plotData %>% 
  filter(!(str_detect(state,'Total'))) %>%
  group_by(census_division,state) %>%
  summarize(relativeExc = max(relExcMed,na.rm=T)) %>% 
  ungroup() %>%
  arrange(census_division,relativeExc) %>%
  pull(state)

sortedStates <- c(sortedStates,paste('Total -',sortedDivisions[-10]),'Nation Total')
statesNum <- length(sortedStates)
sortedLetters <- sort(c(letters,LETTERS,paste0(letters,LETTERS)),decreasing = T)[1:statesNum]

sortedDivisionsS <- plotData %>% 
  filter(!(str_detect(state,'Total'))) %>%
  group_by(census_division,state) %>%
  summarize(relativeExc = max(relExcMed,na.rm=T)) %>% 
  ungroup() %>%
  arrange(census_division,relativeExc) %>%
  pull(census_division)

sortedStatesAndDiv <- str_c(sortedStates,' (',
                            sapply(str_match_all(sortedDivisionsS,'[A-Z]+'),function(x) str_c(x,collapse='')),
                            ')')

plotData <- plotData %>%
  mutate(stateLetter = factor(state,
                        levels=sortedStates,
                        labels=sortedLetters),
         state = factor(state,
                        levels=sortedStates,
                        labels=sortedStatesAndDiv),
         census_division = factor(census_division,
                                  levels = sortedDivisions))

```

```{r}

stateIDs <- plotData %>%
  group_by(census_division,state) %>%
  summarize(groupCode = cur_group_id()) %>%
  ungroup() %>%
  group_by(census_division) %>%
  mutate(stateCode = 1:n()) %>%
  ungroup()
  
plotData <- plotData %>%
  left_join(stateIDs,by=c('state','census_division'))

```

```{r, fig.height=10, fig.width=6}

plotData <- plotData %>%
  group_by(state,metroCat2) %>%
  mutate(relExcMedLead = lead(relExcMed))

```

```{r, fig.height=10, fig.width=6}

allDates <- unique(pull(plotData,monthYear))
  
ridgesGraph <- plotData %>%
  ggplot() +
  #geom_tile(mapping=aes(x=monthYear,y=state,width=31,fill=deaths/expDeathsMed)) +
  geom_ridgeline_gradient(mapping=aes(x=monthYear,
                                      height=relExcMed,
                                      y=stateLetter,
                                      fill=as.numeric(relativeExcDiscrete)),
                               color=NA,
                               stat='identity',
                               scale=1.5) +
  geom_segment(mapping=aes(x=monthYear,
                           xend = lead(monthYear),
                           y = stateCode + relExcMed*1.5,
                           yend = stateCode + relExcMedLead*1.5,
                           linetype=significant)) +
  geom_vline(xintercept=make_date(2020,3,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2020,9,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2020,10,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,2,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,8,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,10,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2021,11,1),linetype='dotted') +
  geom_vline(xintercept=make_date(2022,2,1),linetype='dotted') +  
  annotate('text',x=make_date(2020,6,1),y=0.75,label='Initial Wave',size=3) +
  annotate('text',x=make_date(2020,12,1),y=0.75,label='Winter Peak',size=3) +
  annotate('text',x=make_date(2021,9,1),y=0.75,label='Delta',size=3) +
  annotate('text',x=make_date(2021,12,15),y=0.75,label='Omicron',size=3) +
  scale_x_date(breaks=allDates,date_labels="%b-%y") +
  scale_y_discrete(breaks=sortedLetters,labels=sortedStates) +
  scale_fill_distiller(palette='Oranges',direction = 1,na.value = 'grey90',
                       breaks=1:8,
                       labels=c('<=20%','(20%,40%]','(40%,60%]',
                                '(60%,80%]','(80%,100%]','(100%,150%]',
                                '(150%,200%]','>200%')) +
  scale_linetype_manual(values=c('dotted','solid')) +
  labs(y='',
       x = '',
       fill='Relative\nExcess (%)',
       linetype='Probability of\nRelative Excess > 0') +
  facet_grid(census_division ~ metroCat2,scales = "free_y", space = "free_y") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        legend.position = 'bottom',
        legend.key.width = unit(0.5,'cm'),
        legend.title = element_text(hjust=0.5),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle=90,vjust=0.2)) +
  guides(linetype=guide_legend(nrow = 2),
         fill=guide_legend(title.hjust = 0)) # No idea why this made the legend discrete

ridgesGraph

```

```{r}

pdf(here::here('figures','ridgesGraphAlt.pdf'), height = 16, width = 10)

ridgesGraph

dev.off()

```

```{r}

annotateData <- tibble(x=c(make_date(2020,6,1),
                           make_date(2020,12,1),
                           make_date(2021,9,1),
                           make_date(2021,12,15)),
                       y=c(-150,-150,-100,-100),
                       label=c('Initial\nWave',
                               'Winter\nPeak',
                               'Delta','Omicron'),
                       state='Louisiana (WSC)')

rectData <- rbind(tibble(state = unique(pull(plotData,state)),
                         xmin=make_date(2020,2,15),
                         xmax=make_date(2020,8,15)),
                  tibble(state = unique(pull(plotData,state)),
                         xmin=make_date(2020,9,15),
                         xmax=make_date(2021,1,15)),
                  tibble(state = unique(pull(plotData,state)),
                         xmin=make_date(2021,7,15),
                         xmax=make_date(2021,9,15)),
                  tibble(state = unique(pull(plotData,state)),
                         xmin=make_date(2021,10,15),
                         xmax=make_date(2022,1,15)))

rectData <- plotData %>%
  group_by(census_division,state) %>%
  summarise(ymin=0,
            ymax=max(relExcMed*100)) %>%
  ungroup() %>%
  right_join(rectData,by='state') %>%
  filter(!str_detect(state,'Total'))  

```


```{r, fig.height=10, fig.width=6}

allDates <- unique(pull(plotData,monthYear))
  
barTimeGraph <- plotData %>%
  filter(!str_detect(state,'Total'))  %>%
  ggplot() +
  geom_col(mapping=aes(x=monthYear,
                       y=-50),
                       fill=NA,
                       color=NA,) +
  geom_rect(data=rectData,
            mapping=aes(xmin=xmin,xmax=xmax,
                        ymin=ymin,ymax=ymax),
            alpha=0.3) +
  geom_col(mapping=aes(x=monthYear,
                       y=relExcMed*100,
                       fill=as.numeric(relativeExcDiscrete),
                       size=significant),
           color='black') +
  geom_text(data=annotateData,mapping=aes(x=x,y=y,label=label),size=4,vjust=0) +
  scale_x_date(breaks=allDates,date_labels="%b-%y") +
  scale_y_continuous(breaks=c(0,25,150)) +
  scale_fill_distiller(palette='Oranges',direction = 1,na.value = 'grey90',
                       breaks=1:8,
                       labels=c('<=20%','(20%,40%]','(40%,60%]',
                                '(60%,80%]','(80%,100%]','(100%,150%]',
                                '(150%,200%]','>200%')) +
  scale_size_manual(values=c(0.2,0.5)) +
  labs(y='Relative\nExcess (%)',
       x = '',
       fill='Relative\nExcess (%)',
       size='Probability of\nRelative Excess > 0') +
  facet_grid(factor(state, levels=sortedStatesAndDiv) ~ metroCat2,
               scales = "free_y", space = "free_y",
               switch = 'y') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.spacing.y = unit(-0.9,'lines'),
        legend.position = 'bottom',
        legend.key.width = unit(0.5,'cm'),
        legend.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle=90),
        axis.text.y=element_text(size=7),
        strip.placement = "outside",
        strip.text.y.left = element_text(angle=0)) +
  guides(linetype=guide_legend(nrow = 2),
         fill=guide_legend(title.hjust = 0),
         size=guide_legend(override.aes=aes(fill='white'))) 
barTimeGraph

```

```{r}

pdf(here::here('figures','barTimeGraph.pdf'), height = 16, width = 12)

barTimeGraph

dev.off()

```
