---
title: "Predictors of Excess Mortality"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(INLA)
library(lubridate)
library(here)
library(tidyverse)

```

```{r, echo=FALSE, warning=F, message=F}

# Setting working directories

rm(list=ls())

here::i_am('R/simCreation.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

set.seed(42)

```

```{r, echo=F, message=F, warning=F}

# Reading data

ACData <- tibble(arrow::read_feather(here::here(outDir,'ACData.feather')))
ACYearlyData <- tibble(arrow::read_feather(here::here(outDir,'ACYearlyData.feather')))
COVIDYearlyData <- tibble(arrow::read_feather(here::here(outDir,'COVIDYearlyData.feather')))
popData <- tibble(arrow::read_feather(here::here(outDir,'popDataMonthly.feather')))
popDataYearly <- tibble(arrow::read_feather(here::here(outDir,'popDataYearly.feather')))
countySets <- tibble(arrow::read_feather(here::here(outDir,'countySetsFinal.feather')))
states <- read_csv(here::here(inDir,'utilities','states.csv'),
                   col_types = cols(state=col_character(),
                                    stateStr=col_character(),
                                    stateFIPS=col_integer()))

```

```{r, echo=F}

# We load the draws from the posterior distribution

load(here::here('R','RObjects','simulations.RData'))

```

```{r}

simDataMonthly <- ACData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id()) %>%
  ungroup() %>%
  group_by(csCode) %>%
  mutate(csCode = cur_group_id(),
         csCode2 = csCode) %>%
  ungroup() %>%
  group_by(stateFIPS) %>%
  mutate(stateFIPS = cur_group_id()) %>%
  ungroup() %>%
  mutate(CDR = if_else(year>2019,NA_real_,CDR)) %>%
  arrange(FIPSCode,year,month)

```

```{r}

death.draws <- apply(rate.draws,M=1,function(x) rpois(n.sim,x))

```

```{r}

simulationsMonthly <- as_tibble(t(death.draws))

simulationsMonthly <- simulationsMonthly %>% 
  mutate(year = ACData %>% pull(year),
         month = ACData %>% pull(month),
         monthYear = make_date(year=year,month=month,day=1),
         FIPSCode = ACData %>% pull(FIPSCode),
         csCode = ACData %>% pull(csCode),
         stateFIPS = ACData %>% pull(stateFIPS),
         pop = ACData %>% pull(pop)) %>%
  relocate(FIPSCode,csCode,stateFIPS,year,month,monthYear,pop)

```

```{r}

firstMonth <- 3
lastMonth <- 12

simulationsFIPSMonthly <- simulationsMonthly %>%
  filter(monthYear >= make_date(2020,firstMonth,1),
         monthYear <= make_date(2021,lastMonth,1)) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(across(V1:V1000, ~ sum(.x))) %>%
  ungroup() 

simulationsFIPSMonthly <- simulationsFIPSMonthly %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','stateFIPS','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths,
         nonCOVIDexcess = excDeaths-imputedCOVIDDeaths) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            nonCovidExcCDRLow = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.05)),
            nonCovidExcCDRMed = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.5)),
            nonCovidExcCDRUp = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.95)),
            COVIDExcRatio = quantile(imputedCOVIDDeaths/excDeaths,probs=c(0.5),na.rm=T))

```

```{r, echo=F}

# Computing overall distribution of deaths by month

monthWeights <- ACData %>%
  filter(year<2020) %>%
  group_by(FIPSCode) %>%
  filter(n()==max(n())) %>%
  ungroup() %>%
  group_by(month) %>%
  summarize(monthTotal = sum(deaths,na.rm=T)) %>%
  ungroup() %>%
  mutate(monthWeight = monthTotal/sum(monthTotal)) %>%
  select(month,monthWeight)

monthWeights <- monthWeights %>% pull(monthWeight)

```

```{r}

simDataYearly <- ACYearlyData %>%
  group_by(FIPSCode) %>%
  mutate(FIPSCode = cur_group_id()) %>%
  ungroup() %>%
  group_by(csCode) %>%
  mutate(csCode = cur_group_id(),
         csCode2 = csCode) %>%
  ungroup() %>%
  group_by(stateFIPS) %>%
  mutate(stateFIPS = cur_group_id()) %>%
  ungroup() %>%
  mutate(CDR = if_else(year>2019,NA_real_,CDR)) %>%
  arrange(FIPSCode,year)

```

```{r}

death.draws.y <- apply(rate.draws.y,M=1,function(x) rpois(n.sim,x))

```

```{r}

simulationsYearly <- as_tibble(t(death.draws.y))

simulationsYearly <- simulationsYearly %>% 
  mutate(year = ACYearlyData %>% pull(year),
         FIPSCode = ACYearlyData %>% pull(FIPSCode),
         csCode = ACYearlyData %>% pull(csCode),
         stateFIPS = ACYearlyData %>% pull(stateFIPS),
         pop = ACYearlyData %>% pull(pop))

```

```{r}

simulationsFIPSYearly <- simulationsYearly %>%
  filter(year >= 2020,
         year <= 2021)

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  mutate(across(V1:V1000, ~ if_else(year == 2020,
                                    .x*sum(monthWeights[firstMonth:12]),
                                    .x*sum(monthWeights[1:lastMonth])))) %>%
  select(-pop)

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','stateFIPS','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expDeaths') %>%
  mutate(excDeaths = imputedDeaths-expDeaths,
         nonCOVIDexcess = excDeaths-imputedCOVIDDeaths) %>%
  group_by(year,FIPSCode,csCode,stateFIPS) %>%
  summarize(expDeathsLow = quantile(expDeaths,probs=c(0.05)),
            expDeathsMed = quantile(expDeaths,probs=c(0.5)),
            expDeathsUp = quantile(expDeaths,probs=c(0.95)),
            excDeathsLow = quantile(excDeaths,probs=c(0.05)),
            excDeathsMed = quantile(excDeaths,probs=c(0.5)),
            excDeathsUp = quantile(excDeaths,probs=c(0.95)),
            nonCovidExcCDRLow = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.05)),
            nonCovidExcCDRMed = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.5)),
            nonCovidExcCDRUp = quantile(nonCOVIDexcess/(pop/100000),probs=c(0.95)),
            COVIDExcRatio = quantile(imputedCOVIDDeaths/excDeaths,probs=c(0.5),na.rm=T))

simulationsFIPSYearly <- simulationsFIPSYearly %>%
  rename_with(~ paste0(.x,'SC'), expDeathsLow:COVIDExcRatio)

```

```{r, echo=F}

# We load the data on counties for which the yearly model should perform
# better than the monthly model

monthlyModelPerformance <- read_csv(here::here(outDir,'monthlyModelPerformance.csv'),
                                    col_types = cols(FIPSCode = col_character(),
                                                     meanDifference = col_double()))
  
```

```{r, echo=F}

# We set which estimate to used based on the relative average error of the 

finalSimsFIPS <- simulationsFIPSMonthly  %>%
  left_join(simulationsFIPSYearly,by=c('csCode','FIPSCode','year','simNum')) %>%
  left_join(ACYearlyData,by=c('FIPSCode','csCode','year')) %>%
  left_join(select(COVIDYearlyData,
                   FIPSCode,year,
                   COVIDDeaths,imputedCOVIDDeaths),
            by=c('FIPSCode','year')) %>%
  left_join(monthlyModelPerformance,by='FIPSCode') %>%
  mutate(meanDifference = if_else(is.na(meanDifference),0,meanDifference),
         expDeaths = if_else(meanDifference>0.1,expDeathsSC,expDeaths),
         excDeaths = if_else(meanDifference>0.1,excDeathsSC,excDeaths),
         nonCOVIDexcess = if_else(meanDifference>0.1,nonCOVIDexcessSC,nonCOVIDexcess)) %>%
  select(csCode,FIPSCode,year,simNum,
         imputedDeaths,imputedCOVIDDeaths,
         expDeaths,excDeaths,nonCOVIDexcess)

```

```{r, echo=FALSE, message=F, warning=F}

finalSimsFIPS <- finalSimsFIPS %>%
  rename(deaths = imputedDeaths,
         COVIDDeaths = imputedCOVIDDeaths)
  
```

```{r, echo=FALSE, message=F, warning=F}

save(finalSimsFIPS,file = here::here(outDir,'finalSimsFIPS.RData'))
  
```
