---
title: "Summary Table"
author: "Eugenio Paglino"
date: \today
output: 
  html_document
---

```{r, echo=F, message=F,warning=F}

# Loading necessary packages

library(tidyverse)
library(kableExtra)
library(here)

```

```{r, echo=FALSE, warning=F, message=F}

rm(list=ls())

here::i_am('R/summaryTable.Rmd')

inDir <- here::here('data','input')
outDir <- here::here('data','output')

```

```{r, echo=F, message=F, warning=F}

exMortEstimatesAC <- read_csv(here::here(outDir,'exMortEstimatesINLA.csv'))

```

```{r, echo=FALSE, warning=F, message=F}

## Metropolitan status
metro <- read_csv(here::here(inDir,'utilities','FIPSmetroregion4cat.csv'))
metro <- metro %>%
  select(FIPSCode = fips,
         metroName = metroname) %>%
  mutate(FIPSCode = if_else(nchar(FIPSCode)<5,paste0('0',FIPSCode),as.character(FIPSCode)),
         metroName = case_when(metroName == 'Nonmetro' ~ 'Non Metro',
                               metroName == 'Md/Sm metro' ~ 'Medium/Small',
                               metroName == 'Lg fringe metro' ~ 'Large Fringe' ,
                               metroName == 'Lg central metro' ~ 'Large Central'))
  

exMortEstimatesAC <- exMortEstimatesAC %>%
  left_join(metro, by = 'FIPSCode')

```

```{r, echo=FALSE, warning=F, message=F}

addNonMetro <- c('02068','02105','02198','02230','02275','02282', 
                 '02013','02016','02164','02270','46113','02130',
                 '02188','02290','04012','30067')

addLgFringeMetro <- c('08001','08014')
addMdSmMetro <- c('08013','08123','51515')

## fill out missing metro
exMortEstimatesAC <- exMortEstimatesAC %>%
  mutate(metroName = case_when(FIPSCode %in% addNonMetro ~ "Non Metro",
                               FIPSCode %in% addLgFringeMetro ~ "Large Fringe",
                               FIPSCode %in% addMdSmMetro ~ "Medium Small",
                               TRUE ~ metroName))

```

```{r, echo=FALSE, warning=F, message=F}

## BEA regions
BEARegions <- read_rds(here::here(inDir,'utilities','stateBEARegionCrosswalk.rds'))
BEARegions <- BEARegions %>%
  select(stateStr = state_abb,
         BEARegion = region_bea)

exMortEstimatesAC <- exMortEstimatesAC %>%
  left_join(BEARegions, by = 'stateStr')

```

```{r, echo=FALSE, message=F, warning=F}

popOffset <- 100000
adj2020 <- 10/12
adj2021 <- 12/12

tableDataAC <- exMortEstimatesAC %>%
  drop_na() %>%
  group_by(BEARegion,metroName) %>%
  summarize(excDeaths2020 = sum(excDeathsMed2020),
            COVIDDeaths2020 = sum(COVIDDeaths2020),
            COVIDExcRatio2020 = COVIDDeaths2020/excDeaths2020,
            excDeathRate2020 = popOffset*excDeaths2020/(sum(pop2020)*adj2020),
            COVIDDeathRate2020 = popOffset*COVIDDeaths2020/(sum(pop2020)*adj2020),
            excDeaths2021 = sum(excDeathsMed2021),
            COVIDDeaths2021 = sum(COVIDDeaths2021),
            COVIDExcRatio2021 = COVIDDeaths2021/excDeaths2021,
            excDeathRate2021 = popOffset*excDeaths2021/(sum(pop2021)*adj2021),
            COVIDDeathRate2021 = popOffset*COVIDDeaths2021/(sum(pop2021)*adj2021)) %>%
  ungroup()

tableDataAC <- exMortEstimatesAC %>%
  drop_na() %>%
  group_by(BEARegion) %>%
  summarize(excDeaths2020 = sum(excDeathsMed2020),
            COVIDDeaths2020 = sum(COVIDDeaths2020),
            COVIDExcRatio2020 = COVIDDeaths2020/excDeaths2020,
            excDeathRate2020 = popOffset*excDeaths2020/(sum(pop2020)*adj2020),
            COVIDDeathRate2020 = popOffset*COVIDDeaths2020/(sum(pop2020)*adj2020),
            excDeaths2021 = sum(excDeathsMed2021),
            COVIDDeaths2021 = sum(COVIDDeaths2021),
            COVIDExcRatio2021 = COVIDDeaths2021/excDeaths2021,
            excDeathRate2021 = popOffset*excDeaths2021/(sum(pop2021)*adj2021),
            COVIDDeathRate2021 = popOffset*COVIDDeaths2021/(sum(pop2021)*adj2020)) %>%
  mutate(metroName = 'Region Total') %>%
  ungroup() %>%
  bind_rows(tableDataAC)

tableDataAC <- exMortEstimatesAC %>%
  drop_na() %>%
  group_by(metroName) %>%
  summarize(excDeaths2020 = sum(excDeathsMed2020),
            COVIDDeaths2020 = sum(COVIDDeaths2020),
            COVIDExcRatio2020 = COVIDDeaths2020/excDeaths2020,
            excDeathRate2020 = popOffset*excDeaths2020/(sum(pop2020)*adj2020),
            COVIDDeathRate2020 = popOffset*COVIDDeaths2020/(sum(pop2020)*adj2020),
            excDeaths2021 = sum(excDeathsMed2021),
            COVIDDeaths2021 = sum(COVIDDeaths2021),
            COVIDExcRatio2021 = COVIDDeaths2021/excDeaths2021,
            excDeathRate2021 = popOffset*excDeaths2021/(sum(pop2021)*adj2021),
            COVIDDeathRate2021 = popOffset*COVIDDeaths2021/(sum(pop2021)*adj2021)) %>%
  mutate(BEARegion = 'Total') %>%
  ungroup() %>%
  bind_rows(tableDataAC)
  
tableDataAC <- exMortEstimatesAC %>%
  drop_na() %>%
  summarize(excDeaths2020 = sum(excDeathsMed2020),
            COVIDDeaths2020 = sum(COVIDDeaths2020),
            COVIDExcRatio2020 = COVIDDeaths2020/excDeaths2020,
            excDeathRate2020 = popOffset*excDeaths2020/(sum(pop2020)*adj2020),
            COVIDDeathRate2020 = popOffset*COVIDDeaths2020/(sum(pop2020)*adj2020),
            excDeaths2021 = sum(excDeathsMed2021),
            COVIDDeaths2021 = sum(COVIDDeaths2021),
            COVIDExcRatio2021 = COVIDDeaths2021/excDeaths2021,
            excDeathRate2021 = popOffset*excDeaths2021/(sum(pop2021)*adj2021),
            COVIDDeathRate2021 = popOffset*COVIDDeaths2021/(sum(pop2021)*adj2021)) %>%
  mutate(BEARegion = 'Total',
         metroName = 'Total') %>%
  bind_rows(tableDataAC)

tableDataAC <- tableDataAC %>%
  arrange(BEARegion,metroName) %>%
  slice(45,41:44,
        5,1:4,10,6:9,15,11:14,
        20,16:19,25,21:24,
        30,26:29,35,31:34,
        40,36:39)

```

```{r, echo=F}

tableDataAC %>%
  relocate(BEARegion,metroName) %>%
  kable(col.names = c(c('BEA Region','Metro Status'),
                      rep(c('Excess','COVID','Ratio','Excess','COVID'),2)),
        digits = c(0,0,rep(c(0,0,3,0,0),2)),
        booktabs=T,
        linesep=c('\\addlinespace[2pt]',rep('',3),'\\addlinespace[5pt]'),
        format.args = list(big.mark = ','),
        caption = 'Summary Table - All Causes - BEA Region and Metro Status') %>%
  add_header_above(c(" " = 2, rep(c("Number of Deaths" = 3, "Rates per 100,000 PY" = 2),2))) %>%
  add_header_above(c(" " = 2, "2020" = 5, "2021" = 5)) %>%
  kable_styling(font_size = 7.5)

```

```{r, echo=F}

popOffset <- 100000
adj2020 <- 10/12
adj2021 <- 12/12

tableDataAC <- exMortEstimatesAC %>%
  drop_na() %>%
  group_by(state) %>%
  summarize(excDeaths2020 = sum(excDeathsMed2020),
            COVIDDeaths2020 = sum(COVIDDeaths2020),
            COVIDExcRatio2020 = COVIDDeaths2020/excDeaths2020,
            excDeathRate2020 = popOffset*excDeaths2020/(sum(pop2020)*adj2020),
            COVIDDeathRate2020 = popOffset*COVIDDeaths2020/(sum(pop2020)*adj2020),
            excDeaths2021 = sum(excDeathsMed2021),
            COVIDDeaths2021 = sum(COVIDDeaths2021),
            COVIDExcRatio2021 = COVIDDeaths2021/excDeaths2021,
            excDeathRate2021 = popOffset*excDeaths2021/(sum(pop2021)*adj2021),
            COVIDDeathRate2021 = popOffset*COVIDDeaths2021/(sum(pop2021)*adj2021)) %>%
  ungroup()

```

```{r, echo=F}

tableDataAC %>%
  relocate(state) %>%
  kable(col.names = c(c('State'),
                      rep(c('Excess','COVID','Ratio','Excess','COVID'),2)),
        digits = c(0,rep(c(0,0,3,0,0),2)),
        booktabs=T,
        format.args = list(big.mark = ','),
        caption = 'Summary Table - All Causes - States') %>%
  add_header_above(c(" " = 1, rep(c("Number of Deaths" = 3, "Rates per 100,000 PY" = 2),2))) %>%
  add_header_above(c(" " = 1, "2020" = 5, "2021" = 5)) %>%
  kable_styling(font_size = 7.5)

```